### PR TITLE
Eliminate compiler warning

### PR DESCRIPTION
**Pull request by OFFTKP**

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
This needs to be merged expeditiously

**Comment by OFFTKP** [comment]
Amazing change! + 20000 fps!

**Comment by raphaelthegreat** [comment]
Omg can confirm

**Comment by wheremyfoodat** [comment]
> Amazing change! + 20000 fps!

Does this fix the Amygdala fight in BB?

**Comment by OFFTKP** [comment]
> > Amazing change! + 20000 fps!
> 
> Does this fix the Amygdala fight in BB?

If you joke too much about fixes in BB you might generate a week's worth of videos

**Pull request merged**
