### PR TITLE
Implement V_LSHL_B64 opcode

### PR DESCRIPTION
**Pull request by greggameplayer**
This opcode is needed by CUSA00006 (Knack).

### CODE REVIEW

**Comment by Graubek** [comment]
Knack log
[shad_log.txt](https://github.com/user-attachments/files/16760019/shad_log.txt)


```
[Debug] <Critical> liverpool.cpp:ProcessGraphics:180: Unreachable code!
Invalid PM4 type 0
```

**Comment by bigol83** [comment]
> Knack log [shad_log.txt](https://github.com/user-attachments/files/16759628/shad_log.txt)
> 
> ```
> [Debug] <Critical> liverpool.cpp:ProcessGraphics:180: Unreachable code!
> Invalid PM4 type 0
> ```

Report this here too please 

https://github.com/shadps4-emu/shadPS4/issues/496

**Comment by polybiusproxy** [comment]
FYI the type 0 PM4 is most likely the cause of a missing packet that wasn't written. Are there any stubbed Gnm functions on the log?

**Comment by StevenMiller123** [comment]
@Graubek I think you uploaded the wrong log.

**Comment by Graubek** [comment]
> @Graubek I think you uploaded the wrong log.

Fixed

**Comment by 0xsegf4ult** [comment]
This only works when both operands are immediate and equal to 0?
I actually had a working implementation on my fork so I opened a PR  #613

**Comment by raphaelthegreat** [comment]
The 64bit shifts have only been observed with zero operands so far, so I feel it's simpler to implement them as such for now. Seems compiler emitted pattern for clearing 2 sequential vgprs with 1 instruction. It makes code a bit simpler as it avoids the pack/unpack ir calls.

**Comment by 0xsegf4ult** [comment]
I caught this after hacking around drawindirect in Bloodborne but I did not check if they are zero operands
I'll go get a shader dump and see

**Comment by 0xsegf4ult** [comment]
Yeah nevermind this one is the same
> v_lshl_b64      v[2:3], 0, 0

Do you want me to incorporate this PR into mine, or just leave out the changes?

**Comment by raphaelthegreat** [comment]
I will probably just merge this one since it's specialized for this opcode

**Comment by 0xsegf4ult** [comment]
All right just consider cherry-picking this
[b6d08c6](https://github.com/shadps4-emu/shadPS4/pull/613/commits/b6d08c6385182d5c3a5881e2ba45ca5e0d729007)
S_CMPK_EQ_U32 is plain broken
The rest does not matter anyways, maybe adding BitwiseOr64 to constant propagation but thats it

**Comment by raphaelthegreat** [comment]
Feel free to rebase your PR with this patch and I will merge that as well, thanks for bugfix

**Comment by Exhigh** [comment]
~~Creating a separate PR with just those changes should help~~

**Pull request merged**
