### PR TITLE
Better screenshots for 0.3.0

### PR DESCRIPTION
**Pull request by Xphalnos**
@polybiusproxy 0.3.0 is released!
I removed the "Sister Projects" part because it already exists in "Special Thanks".

Before:
Before

After:
After

### CODE REVIEW

**Comment by raphaelthegreat** [comment]
I think in-game screenshots might be better

**Comment by Xphalnos** [comment]
Can someone send me ingame screenshots of Bloodborne, Resident Evil 4, Red Dead Redemption and Dark Souls. (They all crash after the menu on my Intel Integrated Graphics)

**Comment by polybiusproxy** [comment]
I agree, in-game screenies would be better.
Here's one I've just taken @Xphalnos 
image

**Comment by ElBread3** [comment]
I can definitely provide
screenshot1

**Comment by polybiusproxy** [comment]
image

**Comment by luevano** [comment]
Can you squeeze in this PR the removal of hardcoded shadps4-emu/shadPS4 github links? I believe you can use relative URLs for the images, that way they're not broken on mirrors (like gitea).

Also, the `<a>` tag is broken:

https://github.com/shadps4-emu/shadPS4/blob/f79da986e3c4783e124a565fc8fc3ff917783ee6/README.md?plain=1#L27-L33

Github, doesn't care I guess, and renders it just fine; but it bleeds out on gitea for example.

I know these are minor, but seem too simple for a separate PR.

**Comment by Xphalnos** [comment]
Screenshots are updated!

**Comment by f1amy** [comment]
This now needs conflicts fixed, sry

**Comment by Xphalnos** [comment]
Forced to close the commit due to this [**commit**](https://github.com/shadps4-emu/shadPS4/pull/1079).
I reopen one without conflict.

**Comment by f1amy** [comment]
@Xphalnos sorry, why could you not just rebase?

**Comment by Xphalnos** [comment]
> @Xphalnos sorry, why could you not just rebase?

I didn't rebase it because I had other changes to make (**https://github.com/shadps4-emu/shadPS4/pull/1122**)

**Pull request closed without merging**
