### PR TITLE
core: Some small pad stubs

### PR DESCRIPTION
**Pull request by dima-xd**
Some small stubs needed for GT

### CODE REVIEW

**Comment by DanielSvoboda** [comment]
in scePadSetLightBar:

```cpp
        if (pParam->r < 0xD && pParam->g < 0xD && pParam->b < 0xD) {
            LOG_INFO(Lib_Pad, "scePadSetLightBar ORBIS_PAD_ERROR_INVALID_LIGHTBAR_SETTING");
            return ORBIS_PAD_ERROR_INVALID_LIGHTBAR_SETTING;
        }
```

**Comment by dima-xd** [comment]
> in scePadSetLightBar:
> 
> ```c++
>         if (pParam->r < 0xD && pParam->g < 0xD && pParam->b < 0xD) {
>             LOG_INFO(Lib_Pad, "scePadSetLightBar ORBIS_PAD_ERROR_INVALID_LIGHTBAR_SETTING");
>             return ORBIS_PAD_ERROR_INVALID_LIGHTBAR_SETTING;
>         }
> ```

thanks, noticed that too in decompiled scePadSetLightBar

**Comment by raphaelthegreat** [comment]
This good for merge?

**Comment by dima-xd** [comment]
> This good for merge?

Yep. I am done with this PR

**Pull request merged**
