### PR TITLE
Save lib fixes III

### PR DESCRIPTION
**Pull request by viniciuslrangel**

### CODE REVIEW

**Comment by ElBread3** [comment]
Does indeed fix the Lego game, you can reach this screen again
legodimsavefixed

**Comment by gandalfthewhite19890404** [comment]
image
I think it should me merged ASAP

**Comment by viniciuslrangel** [comment]
@gandalfthewhite19890404 I'll do one more quick-fix before merging it

**Comment by viniciuslrangel** [comment]
@georgemoralis mergeable!

**Pull request merged**
