### PR TITLE
Surface management rework (3/3)

### PR DESCRIPTION
**Pull request by psucien**
Major changes:
- Initial support for overlapping images. Currently used for mip gen scenarios, can be extended to aliasing in future
- Handy debug features: rdoc markers, NV checkpoints, GPU assisted validation
- Gnm driver functions: `sceGnmGetGpuCoreClockFrequency` and `sceGnmSetVgtControl`

And small fixes here and there

### CODE REVIEW

**Comment by bigol83** [comment]
With latest commit Red Dead Redemption now crashes when trying to render main menu. This is the error 

[Debug] <Critical> vk_scheduler.cpp:SubmitExecution:168: Unreachable code!
Device lost during submit: vk::Queue::submit: ErrorDeviceLost

Log 
[shad_log.txt](https://github.com/user-attachments/files/16507849/shad_log.txt)

**Comment by bigol83** [comment]
Do you want me to test if RDR still crashes?

**Comment by gandalfthewhite19890404** [comment]
RDR still crashes:
```
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:377: Unsupported tiled image: R8G8B8A8Unorm (Texture_MacroTiled)
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:377: Unsupported tiled image: R8G8B8A8Unorm (Texture_MacroTiled)
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:86: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:86: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:377: Unsupported tiled image: R16Sfloat (Texture_MacroTiled)
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:86: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:86: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:86: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:86: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:377: Unsupported tiled image: R8Unorm (Texture_MacroTiled)
[Debug] <Critical> vk_scheduler.cpp:SubmitExecution:168: Unreachable code!
Device lost during submit: vk::Queue::submit: ErrorDeviceLost
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:86: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:86: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:86: Storage image (num_comps = 2) requires swizzling [RG01]
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:86: Storage image (num_comps = 1) requires swizzling [R001]
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:377: Unsupported tiled image: R8G8B8A8Srgb (Display_MacroTiled)
[Render.Vulkan] <Info> renderer_vulkan.cpp:GetRenderFrame:357: Got render frame, remaining 1
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:443: name=d11mutex, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:443: name=d11mutex, result=0
```

**Comment by EmulationChannel** [comment]
RED DEAD and ONE PIECE Breaking next with these PRs

**Comment by EmulationChannel** [comment]
RED DEAD PR
[shad_log.txt](https://github.com/user-attachments/files/16570932/shad_log.txt)

**Comment by EmulationChannel** [comment]
Bloodborne 
[shad_log.txt](https://github.com/user-attachments/files/16570934/shad_log.txt)

**Comment by gandalfthewhite19890404** [comment]
RDR crashes after FMV, i5-10400, RTX2060 Super.
Anyone else, confirm pls.

**Comment by bigol83** [comment]
> RDR crashes after FMV, i5-10400, RTX2060 Super. Anyone else, confirm pls.

It always crashed with this PR, @psucien is aware of the issue. It crashes for me too at the same spot.

**Comment by gandalfthewhite19890404** [comment]
> > RDR crashes after FMV, i5-10400, RTX2060 Super. Anyone else, confirm pls.
> 
> It always crashed with this PR, @psucien is aware of the issue. It crashes for me too at the same spot.

There was a videos with fixed graphics, they said it was done with that PR. That is why I asked. Thanks for confirming!!!!

**Comment by EmulationChannel** [comment]
[shad_log.txt](https://github.com/user-attachments/files/16573186/shad_log.txt)
RED DEAD

**Comment by EmulationChannel** [comment]
[shad_log.txt](https://github.com/user-attachments/files/16573358/shad_log.txt)
Bloodborne

**Comment by DeveloperVaibhav1** [comment]
> Do you want me to test if RDR still crashes?

pls test for it too

**Comment by DeveloperVaibhav1** [comment]
> > > RDR crashes after FMV, i5-10400, RTX2060 Super. Anyone else, confirm pls.
> > 
> > 
> > It always crashed with this PR, @psucien is aware of the issue. It crashes for me too at the same spot.
> 
> There was a videos with fixed graphics, they said it was done with that PR. That is why I asked. Thanks for confirming!!!!

same issue with me too

**Comment by DeveloperVaibhav1** [comment]
> With latest commit Red Dead Redemption now crashes when trying to render main menu. This is the error
> 
> [Debug] vk_scheduler.cpp:SubmitExecution:168: Unreachable code! Device lost during submit: vk::Queue::submit: ErrorDeviceLost
> 
> Log [shad_log.txt](https://github.com/user-attachments/files/16507849/shad_log.txt)

It can be done using alterate method

**Comment by DeveloperVaibhav1** [comment]
> [shad_log.txt](https://github.com/user-attachments/files/16573186/shad_log.txt) RED DEAD

Kernel.Fs] <Info> file_system.cpp:sceKernelStat:292: (PARTIAL) path =  default

**Comment by DeveloperVaibhav1** [comment]
> > [shad_log.txt](https://github.com/user-attachments/files/16573186/shad_log.txt) RED DEAD
> 
> Kernel.Fs] file_system.cpp:sceKernelStat:292: (PARTIAL) path = default
NOTE : TO USE DEFAULT PATH OR ELSE IT WONT WORK

**Comment by tteuzru** [comment]
CUSA36843 - RDR won't go ingame with the latest build
[shad_log.txt](https://github.com/user-attachments/files/16742487/shad_log.txt)
rdrshad

**Comment by tteuzru** [comment]
CUSA08692 - Dark Souls Remastered looks like this with the latest build
drkshad
[shad_log.txt](https://github.com/user-attachments/files/16742578/shad_log.txt)

**Comment by bigol83** [comment]
Can confirm Dark Souls remastered regression, but Red Dead Redemption goes ingame for me

Cattura

**Comment by bigol83** [comment]
This fixes Resident Evil main menu compared to main build, but some text boxes are still not correctly rendered

Cattura

Cattura2

**Comment by bigol83** [comment]
Just an update about Red Dead Redemption

Using this PR with RDR 1.04 it loads fine when there is no save data, but if save data is created the emulator crashes on main menu with this error

```
[Debug] <Critical> liverpool.h:unhandled_exception:1097: Unreachable code!
Unhandled exception: vk::Device::waitForFences: ErrorDeviceLost
```
[shad_log.txt](https://github.com/user-attachments/files/16754408/shad_log.txt)

Sometimes it also crashes with this log 

```
[Debug] <Critical> vk_scheduler.cpp:SubmitExecution:202: Unreachable code!
Device lost during submit: vk::Queue::submit: ErrorDeviceLost
```
[shad_log.txt](https://github.com/user-attachments/files/16754463/shad_log.txt)


Here you can see it reaches ingame if there is no save data

Cattura

**Comment by bigol83** [comment]
Dark Souls back to looking like this after the latest updates

Cattura

**Comment by raphaelthegreat** [comment]
Dark Souls needs fragment shader output swizzle to correct the graphics

**Comment by Randomuser8219** [comment]
Screenshot 2024-08-31 115813
Graphics on Namco Museum Archives in the M2 logo and the intro screen are now fixed

**Comment by kvicken** [comment]
Graphical regression with the latest build in CUSA08692 - Dark Souls Remastered
rdrshad2
rdrshad3

**Comment by Ishikudeska** [comment]
have you tested BB? Ik dumb ask, but...?

**Comment by kvicken** [comment]
BB don't go ingame with this build

**Comment by Ishikudeska** [comment]
I see

**Comment by KITT1995** [comment]
This fixes glitched sprites during combat of Phantom Breakers Omnia CUSA19104

**Comment by xzyxzy** [comment]
fixes some problematic character sprites in CUSA05083 - Odin Sphere Leifthrasir https://github.com/shadps4-emu/shadps4-game-compatibility/issues/535

363514336-1e54a99a-d883-4995-8296-ea503cf67573

Fixed:
image

**Review by raphaelthegreat — APPROVED** [review]

**Comment by illyazru** [comment]
Graphical regression in CUSA32836 
Captura de tela 2024-09-04 1828452
Captura de tela 2024-09-04 1830222

**Comment by bigol83** [comment]
Resident Evil HD remaster main menu regression in latest commit compared to earlier commits 

Cattura

**Comment by bigol83** [comment]
Resident Evil 4 now shows nothing, you can hear menu sounds and reach ingame like usual, but the game gives a totally black screen from booting to ingame.

**Comment by Foul-Tarnished** [comment]
I remade bb-hacks into main after this got merged, and I get a blackscreen in Bloodborne (except UI) and it crash after a few seconds in-game

image

**Comment by gandalfthewhite19890404** [comment]
RDR 1.00 now crashing after I reached gameplay with:
[Debug] <Critical> image_info.cpp:ImageInfo:213: Unreachable code!

**Comment by shiiironyanpan** [comment]
Recent hot-fix commit fixed Resident Evil 4, can't confirm RDR and other games mentioned since I don't own them

image

**Pull request merged**
