### PR TITLE
qt_gui: Organize settings page

### PR DESCRIPTION
**Pull request by Exhigh**
* Wire up translations and descriptions for the cursor settings.
* Move controller settings to input tab and rename it to controller (to inline it with how other settings are shown).
* Fixed unnecessary double initialization of the back button setting.
* Organize statements and functions w/ respect to their tabs and some minor QOL changes for the settings UI in general.

### CODE REVIEW

**Comment by georgemoralis** [comment]
#1038 , #1316 , #1319 modifies the same settings file . Cooperate somehow so i can know what to merge ;/

**Comment by Exhigh** [comment]
I feel like the oldest PR (#1308) could get merged and i could rebase my PR. As for PR #1319 it could either be merged separately or i could cherry-pick them with @DanielSvoboda co-authoring this PR. I don't mind either way.

**Comment by georgemoralis** [comment]
#1308 pushed

**Comment by DanielSvoboda** [comment]
1308 has already been merged.
1316 'this' could be next
And leave mine separated for last pr1319, then I can include some calls for translation that are missing

**Pull request merged**
