### PR TITLE
Better screenshots for 0.3.0 + misc changes

### PR DESCRIPTION
**Pull request by Xphalnos**
- I put the best screenshots proposed by the community
- I bumped the new version of Qt that was released yesterday ([**Release notes**](https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.7.3/release-note.md))
- I updated the other sub-modules
- Updating changelog.txt

image

### CODE REVIEW

**Comment by polybiusproxy** [comment]
I'm not quite sure about the submodule updates. CI seems to have passed but has this been tested?

**Comment by Xphalnos** [comment]
> I'm not quite sure about the submodule updates. CI seems to have passed but has this been tested?

I tested on Turok and Red Dead Redemption and it works

**Comment by ElBread3** [comment]
Think we could get a fullscreen screenshot of Bloodborne as the title bar stands out among the others?

**Comment by Xphalnos** [comment]
> Think we could get a fullscreen screenshot of Bloodborne as the title bar stands out among the others?

Done!

**Pull request merged**
