### PR TITLE
Fixed return strict const iterator, replace to range-based loop C++17 and code refactor

### PR DESCRIPTION
**Pull request by GermanAizek**
I am waiting for feedbacks and code review

### CODE REVIEW

**Comment by georgemoralis** [comment]
all ci failure you might have to recheck your code again

**Comment by GermanAizek** [comment]
> all ci failure you might have to recheck your code again

@georgemoralis fix error is successful build

**Review by polybiusproxy — COMMENTED** [review]
Looks good to me. Was this tested with any game @GermanAizek?

**Comment by Hermiten** [comment]
No answer for 1 month, is it still revelant ? @GermanAizek

**Pull request merged**
