### PR TITLE
Use a singleton for instruction decoding

### PR DESCRIPTION
**Pull request by OFFTKP**
We're going to need the decoder in more places soon and don't need to do ZydisDecoderInit everywhere

### CODE REVIEW

**Review by polybiusproxy — COMMENTED** [review]
Why not use the [Singleton](https://github.com/shadps4-emu/shadPS4/blob/main/src/common/singleton.h) class?

**Comment by OFFTKP** [comment]
Ah sure missed it

**Review by polybiusproxy — APPROVED** [review]
Looks good

**Comment by georgemoralis** [comment]
@OFFTKP is that absolute now?

**Comment by OFFTKP** [comment]
Since extrq was merged this isn't needed

**Pull request closed without merging**
