### PR TITLE
Kernel-Related Fixes

### PR DESCRIPTION
**Pull request by StevenMiller123**
I noticed some easy to fix problems while testing some of my games. Please let me know if I should remove any of these changes.

### CODE REVIEW

**Comment by red-prig** [comment]
`off_t` is not equal in size to `size_t` ? or what?
Alignment:
```
 [KernelBatchMapEntry]
  start:64
  offset:64
  length:64
  protection:8
  mtype:8
  pad1:16
  operation:32
```

**Comment by raphaelthegreat** [comment]
Seems off_t is 32bits on some platforms. Strange

**Comment by StevenMiller123** [comment]
When I looked it up, they were the same size, but off_t is signed while size_t is unsigned (I think). I tested on Windows and Ubuntu 23.10, and the change didn't break anything for me.

**Comment by raphaelthegreat** [comment]
Looks good to me

**Pull request merged**
