### PR TITLE
shader_recompiler: using reserve() if possible

### PR DESCRIPTION
**Pull request by GermanAizek**
I think it will be a useful changes

### CODE REVIEW

**Comment by raphaelthegreat** [comment]
This is unnecessary I feel. All containers here are either static_vector or small_vector optimized for common case

**Comment by GermanAizek** [comment]
> This is unnecessary I feel. All containers here are either static_vector or small_vector optimized for common case

We need to review all vectors, whether exact count has already been reserved.

**Comment by GermanAizek** [comment]
@raphaelthegreat maybe I really added reserve unnecessarily.

**Comment by raphaelthegreat** [comment]
Yes aside from the icons one the others are not having any benefit I feel

**Comment by raphaelthegreat** [comment]
Closing this for now, feel free to reopen if really necessary

**Pull request closed without merging**
