### PR TITLE
Fix compilation on linux

### LINKED ISSUE #845: [Linux] Failing to compile on Arch after imgui implementation
using 
`cmake -S . -B build/ -DENABLE_QT_GUI=ON`
`cmake --build . --parallel$(nproc)`

```shell
/shadPS4/src/imgui/renderer/imgui_core.cpp: In function ‘void ImGui::Core::Render(const vk::CommandBuffer&, Vulkan::Frame*)’:
/shadPS4/src/imgui/renderer/imgui_core.cpp:189:5: error: ambiguous overload for ‘operator=’ (operand types are ‘vk::Rect2D’ and ‘<brace-enclosed initializer list>’)
  189 |     };
      |     ^
In file included from /usr/include/vulkan/vulkan.hpp:8579,
                 from /shadPS4/src/video_core/renderer_vulkan/vk_common.h:17,
                 from /shadPS4/src/video_core/renderer_vulkan/vk_platform.h:11,
                 from /shadPS4/src/video_core/renderer_vulkan/vk_instance.h:9,
                 from /shadPS4/src/imgui/renderer/imgui_core.h:6,
                 from /shadPS4/src/imgui/renderer/imgui_core.cpp:9:
/usr/include/vulkan/vulkan_structs.hpp:8142:14: note: candidate: ‘vk::Rect2D& vk::Rect2D::operator=(const VkRect2D&)’
 8142 |     Rect2D & operator=( VkRect2D const & rhs ) VULKAN_HPP_NOEXCEPT
      |              ^~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:8124:10: note: candidate: ‘constexpr vk::Rect2D& vk::Rect2D::operator=(const vk::Rect2D&)’
 8124 |   struct Rect2D
      |          ^~~~~~
/usr/include/vulkan/vulkan_structs.hpp:8124:10: note: candidate: ‘constexpr vk::Rect2D& vk::Rect2D::operator=(vk::Rect2D&&)’
make[2]: *** [CMakeFiles/shadps4.dir/build.make:289: CMakeFiles/shadps4.dir/src/imgui/renderer/imgui_core.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:247: CMakeFiles/shadps4.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
i made sure to update my system and install imgui from the AUR just in case

a bit unrelated but it also throws this warning
```shell
In file included from /shadPS4/externals/dear_imgui/imgui.h:64,
                 from /shadPS4/src/imgui/renderer/imgui_core.cpp:5:
/shadPS4/src/imgui/imgui_config.h:28:100: warning: backslash-newline at end of file
   28 | #define IM_VEC2_CLASS_EXTRA
```

### PR DESCRIPTION
**Pull request by N00byKing**
~~Also, add compile_commands.json to gitignore.~~

~~This file is generated when using the `CMAKE_EXPORT_COMPILE_COMMANDS` flag. It is used by clangd to search header files, and needs to be in the project root (tho I just symlink it).~~

Closes #845

### CODE REVIEW

**Comment by Caliel666** [comment]
can confirm that this fixes my issue, working just fine

**Comment by abouvier** [comment]
You're not supposed to add this kind of file to the project gitignore. I you personally use `clangd`, then add it to your global gitignore. If you're on macOS, add `.DS_Store` to your own `gitignore` (all your projects will benefit from it), etc.

**Comment by N00byKing** [comment]
I mean, the DS_Store files are in the project gitignore :P
If this is a blocker for merge I'll remove it, but tbh I disagree with that reasoning.
Point of the gitignore is to protect from accidentally pushing things, and that only happens when someone does not have the relevant files in the global one.

**Comment by abouvier** [comment]
> I mean, the DS_Store files are in the project gitignore :P 

Yes, 95% of the content of this file should be removed ;)

You will also add the config file of every text editor in existence? Everyone using git should configure their `gitignore` according to their environment :p

A project `gitignore` is for ignoring the files [produced by that project](https://blog.martinhujer.cz/dont-put-idea-vscode-directories-to-projects-gitignore/).

**Comment by N00byKing** [comment]
Alright, removed it :)

**Pull request merged**
