### PR TITLE
wip: added status column for compat data

### PR DESCRIPTION
**Pull request by f8ith**
Addresses #1571 

* data is currently pulled directly from github API, awaiting server infrastructure. This would be rate-limited when the compatibility repo reaches 6k open issues

WIP PR intended to gather opinions about how the status column should behave. In my implementation a dialog appears by default on startup while the emulator fetches compatibility information. The database is saved to a single json under the `game_data`	folder. Then the best available status is selected based on the current platform. 

e.g. on Windows (os-windows -> no os label -> os-linux -> os-macOS)

Edit: Latest commit

image

### CODE REVIEW

**Comment by Hermiten** [comment]
Wonderful.
I didn't try it for now, but I have to idea:

- Put a dialog message when you hover the text to say like for In-game "In-game: You can play the game but there is some glitch and maybe you cannot finish the game"
- A second column with the lastest test date. I don't know how we can retrieve this. Maybe we can cheat by using the last comment on the issue or maybe you can retrieve the last time the milestone was edited
- Somewhere to put what was the last version of the emulator for the test (0.4 for example) ?

All of this are suggestion as the PR is in draft

**Comment by kalaposfos13** [comment]
Hey I opened a PR on your fork fixing the linker error

**Comment by GHU7924** [comment]
> Замечательный. Пока не пробовал, но есть идея:
> 
>     * При наведении курсора на текст поместите диалоговое сообщение, например, «В игре: вы можете играть в игру, но есть какой-то сбой, и, возможно, вы не сможете закончить игру».
> 
>     * Второй столбец с последней датой тестирования. Я не знаю, как мы можем это получить. Возможно, мы сможем обмануть, используя последний комментарий к проблеме, или, может быть, вы сможете узнать, когда в последний раз редактировалась веха.
> 
>     * Куда-нибудь выложить, какая была последняя версия эмулятора для теста (0.4 например)?
> 
> 
> Все это предложения, поскольку PR находится в стадии разработки.

Great ideas

Next
compab

-example of the second column in two versions
-instead of colored circles, we can try to use icons like on the Steam Deck, they are taken as a basis, but I don't know if it will be better or you can leave the existing option
-an example of a dialog box when hovering over the cursor, but here I did not try to draw something normal at all))

**Comment by GHU7924** [comment]
When I started, I got a window, but it hung? Progress just stopped. How long do I have to wait?
I also restarted the emulator several times and there was different progress, 90, 84, 63 it seems, but after that nothing.

If I closed this window, I got this result:

On subsequent restarts, I got this:


Although I was glad to see the update of this PR, but after some thought about it,
I think it's necessary to redo the changes you've made so that they better match the look and style of shadPS4.
In my personal opinion, it would be better to do so:


@DanielSvoboda  As you know, we have the ability to update the emulator manually, there are even two ways to do this.
How would you like to replace the button in the Help section with a button for manually updating the compatibility database?


We also don't have the ability to move columns in places, but I'd like to see what such a sequence would look like, would it be better?..
Serial, Icon, Name, Version, Compatibility, Status Updated, Region, Firmware, Size, Play Time, Path.

**Comment by f8ith** [comment]
> When I started, I got a window, but it hung? Progress just stopped. How long do I have to wait? I also restarted the emulator several times and there was different progress, 90, 84, 63 it seems, but after that nothing. 

I think you're running into github API's limits. If you run the emulator normally this error shouldn't occur as the data is saved to a json and only updated after an hour. In any case there's no need to fix it as it seems there will be a compatibility database on shadps4's website which will remove the need for that part of the code.

**Comment by GHU7924** [comment]
@f8ith the fact is that I start the emulator, a window appears, in seconds it reaches a certain progress and freezes, if I close this window (do not cancel) by interrupting this progress, then I will not have a JSON file.
The path - "emulator folder"\user\game_data - I didn't have a *.json file there..

And so I wanted to record it on video, but apparently an hour later (as you said), the database was updated and I got this file (compatibility_data.json).
Maybe it's not a problem, but either it happens on the first launch, or there was something else.

**Comment by DanielSvoboda** [comment]
When I was doing AutoUpdate, I noticed that the GitHub APIs can only make 60 requests in a one-hour period. If you exceed this limit, these requests will be blocked for a while. You have to be careful not to have too many requests.

**Comment by Hermiten** [comment]
This is a screen of the last version of this PR if someone want to see the progress:

image

**Comment by Hermiten** [comment]
2 suggestions:
- Maybe we can add the link of the status on the compatibility, so we can open github by clicking on it ?
- Also, for a correct design, we can keep the status with the same police and size than others colunm, center, and only show the date + version on hover ?

**Comment by GHU7924** [comment]
As I suggested above, you can do this:

I understand that this is more difficult, but this would be completely consistent with the shadPS4 style.
In any case, the developers have the last word, so I don't insist on it.

> 2 suggestions:
> 
>     * Maybe we can add the link of the status on the compatibility, so we can open github by clicking on it ?
> 
>     * Also, for a correct design, we can keep the status with the same police and size than others colunm, center, and only show the date + version on hover ?

1) You can connect the Serial column to this, when you click on a specific series, you would switch to compatibility search, because it is the same, only the numbers after CUSA change.

>https://github.com/shadps4-emu/shadps4-game-compatibility/issues?q=is%3Aissue+is%3Aopen+CUSA03173
>https://github.com/shadps4-emu/shadps4-game-compatibility/issues?q=is%3Aissue+is%3Aopen+CUSA00004

It turns out that the general part will be a link to which the serial number is appended, if such a thing can be done at all.

>https://github.com/shadps4-emu/shadps4-game-compatibility/issues?q=is%3Aissue+is%3Aopen+

>CUSA03173
>CUSA00004

2) Like this?

But it would be better if it were like this: Status Updated 2024-12-07, v0.4.0

**Comment by Hermiten** [comment]
Yes, exactly @GHU7924 

For the 1: On the serial is a good idea. Maybe add something like an icon "click" to know that we can open it
For the 2: Perfect like this, because every information is here, it's clear and follow the style of the other column

**Comment by GHU7924** [comment]
@Hermiten Like this?

However, I'm not sure if this can be done...

**Comment by f8ith** [comment]
@Hermiten @GHU7924 suggestions have been added

**Comment by GHU7924** [comment]
I think the result is good, the information is there, clicking on the links works.

(Perhaps the font may be a little larger... Or maybe not)

**Comment by Hermiten** [comment]
The result is also good for me. Maybe there will be an update on the UI but like this is enough. Congratulations !
For the "report" part, maybe it's more easier to put it here:

image

Something like "Check report" and if there is no report: "Create a report"


EDIT:
Because I cannot find what you did about the github link on the last version, I see nothing 
image
(My cursor was on it)

**Comment by GHU7924** [comment]
@Hermiten Verification may not be necessary, because when you click, you will be redirected to a page where you can view the report.
Link to Github - Click on the Ingame.

Now: If there is no report, then there is no link and it will be written that the game has not been tested.

What can be done: This is where your idea may come in handy, and when you click on the status of the game, you will be prompted to create a report. You can add information that the game has not been tested, but if you click on the status, you can create a report.


@f8ith If you are going to create a report, then remember that we have a form to fill out.
https://github.com/shadps4-emu/shadps4-game-compatibility/blob/main/.github/ISSUE_TEMPLATE/game_compatibility.yml

**Comment by Hermiten** [comment]
Can you solve the clang format ? And then we will do some final test :)

**Comment by Hermiten** [comment]
Work well for me on Windows !

- [X] Retrieve every games on my list
- [X] The click to open issue work
- [X] UI is fine and we have all information about the last update of the issue (milestone, date)

2 technical questions:
- How does the list update work, is it on every reboot or is there a delay, etc.? 
- I dont have other OS to test but if I understand, the compatibility list is adapted to the OS used ?

Thanks you

**Comment by GHU7924** [comment]
I have this problem again

https://github.com/user-attachments/assets/5d4f1acb-b840-4140-8795-01ad2510e30f

After several restarts, I got the error window again.

error

And I don't think I've managed to make 60 requests in an hour, maybe not even a third.

I'll wait, maybe it'll work in an hour.

**Comment by gandalfthewhite19890404** [comment]
Each title -> new search=new request. So here is limits overflow. Or I'm wrong?

**Comment by GHU7924** [comment]
The thing is, I only managed to open a couple of themes on GitHub, including this one, to download the build. I unpacked the archive, launched the emulator, pointed out the path to the games, then what happened in the video. That is, it happened at the very first launch. As for the games, I have 14 of them at the moment (more for tests, not walkthroughs).


There is also a missing list of games.

**Comment by f8ith** [comment]
Edit: There was a typo in the if-condition. The bug should be fixed

> How does the list update work, is it on every reboot or is there a delay, etc.?

`CompatibilityInfoClass::UpdateCompatibilityDatabase` checks for a file at `user/game_data/compatibility_data.json`. If the file exists and it was last modified within the past hour, then it will read from the file, otherwise updated information will be pulled from github issues. All issues from the repo are pulled in parallel (all >1000 issues); NOT on a per-game basis. So the only way you would run into github API limit is if you update the database more than 5 times in an hour which should not happen unless there is a bug. 

> I dont have other OS to test but if I understand, the compatibility list is adapted to the OS used ?

My parent comment has a short explanation but tldr - the data from the issues is read sequentially like this until an issue with a matching os label is found.
on Windows (os-windows -> no os label -> os-linux -> os-macOS)
on macOS (os-macOS -> no os label -> os-linux -> os-windows)
on Linux (os-linux -> no os label -> os-windows -> os-macOS)

**Comment by GHU7924** [comment]
Build 24bfc41

>Saving new configuration file C:\Users\"Username"\Downloads\shadps4-win64-qt-2024-12-13-24bfc41\user\config.toml

This is recorded in the command line (log), in the progress window again "Frozen progress". I close the Progress window, close the emulator window, and the terminal window is still open.

I don't understand what the problem is. But apparently I'm the only one with it, since no one else has encountered it. But I can't say anything about it.

**Comment by Hermiten** [comment]
For the OS, there is 2 ways:
- Like you did, and it's fine
- Or only Windows for Windows, Linux for Linux and Mac for Mac. If there is no label, it just need to be updated by me or someone else. 

I'm just writing it here to ask opinion what can be the best (And I don't know !)

Can you resolve the clang format ?thanks you

**Comment by GHU7924** [comment]
@f8ith It seems that if I run the emulator as an administrator, then I can work around my problem.

@Hermiten @georgemoralis This is not so much a suggestion as a question.

Should the number of labels be increased? 

I mean, the games are tested on different hardware and then this data is added to the compatibility list.

And in theory, you can add: INTEL CPU, AMD CPU, APPLE CPU, NVIDIA GPU, RADEON GPU, INTEL GPU and may be something else.

For example, I tested the game on my computer and created a compatibility report with the following labels:
os-windows, INTEL CPU, NVIDIA GPU, status-ingame.

And someone else will have another: os-linux, AMD CPU, RADEON GPU, status-menus.

This will definitely complicate things a bit, but I just don't know if it will improve or worsen reporting.

Does it make sense?

**Comment by Hermiten** [comment]
@GHU7924 There will be too much label and will be to hard to maintain it updated. But it make sense
OS multiply everything by 3x (win, linux, mac) so with every card it will be crazz

**Comment by Linear524** [comment]
There should be settings to manually disable compat.-auto-update, because ShadPS4 shouldn't try to go into the Internet if user doesn't want this. And popup window with "auto-update failed" message is pretty annoying right now...
Just try to add this function via checkbox activation inside settings menu please...

**Comment by GHU7924** [comment]
I agree with @Linear524 

Perhaps it should be done this way.
status

You can also place a button here (for example, button "Report/Support") that leads to this address. 

https://github.com/shadps4-emu/shadps4-game-compatibility/issues/new/choose

status3

EDIT:
In my personal opinion, it looks very good.
status4

**Pull request merged**
