### PR TITLE
audio: Accurate audio output timing.

### PR DESCRIPTION
**Pull request by squidbus**
Implements accurate timing for audio output, using a single-buffer queue same as the actual audio out library and a thread to manage audio timing.

This also removes cubeb for now at least as with this fix, SDL seems to be working just as well, and debugging is simpler if we just have to worry about one audio backend configuration. We can re-add this in the future if needed but for some Windows users it seems to be resulting in strange crashes.

Needs testing with various OSes and games to make sure this works for all audio systems, as the timing might be tight. From my testing it seems to work pretty well on Mac.

### CODE REVIEW

**Comment by squidbus** [comment]
This should fix https://github.com/shadps4-emu/shadPS4/issues/1717 for everyone

**Comment by squidbus** [comment]
Satisfied with the handling of SDL queue stalling now. This can occur if the audio device changes, for example, causing frames to back up within the queue and latency to grow if left unchecked.

**Comment by Emulator-Team-2** [comment]
One Piece Unlimited World Red Deluxe Edition - `Missing Audio`

```
[Lib.AudioOut] <Info> audioout.cpp:sceAudioOutOpen:304: id = 255 port_type = Main index = 0 length = 256 sample_rate = 48000 param_type = Float_8CH attr = None
[Lib.AudioOut] <Error> sdl_audio.cpp:SDLPortBackend:40: Failed to configure SDL audio stream channel map: Wrong number of channels
```
Log:
[shad_log.zip](https://github.com/user-attachments/files/18279941/shad_log.zip)

##

Gintama Rumble - `Missing Audio`

```
[Lib.AudioOut] <Info> audioout.cpp:sceAudioOutOpen:304: id = 255 port_type = Main index = 0 length = 256 sample_rate = 48000 param_type = Float_8CH attr = None
[Lib.AudioOut] <Error> sdl_audio.cpp:SDLPortBackend:40: Failed to configure SDL audio stream channel map: Wrong number of channels
[Lib.AudioOut] <Info> audioout.cpp:sceAudioOutOpen:304: id = 1 port_type = Padspk index = 0 length = 256 sample_rate = 48000 param_type = FloatMono attr = None
[Lib.AudioOut] <Error> sdl_audio.cpp:SDLPortBackend:40: Failed to configure SDL audio stream channel map: Wrong number of channels
[Lib.AudioOut] <Info> audioout.cpp:sceAudioOutOpen:304: id = 255 port_type = Main index = 0 length = 256 sample_rate = 48000 param_type = Float_8CH attr = Restricted
[Lib.AudioOut] <Error> sdl_audio.cpp:SDLPortBackend:40: Failed to configure SDL audio stream channel map: Wrong number of channels
[Lib.AudioOut] <Info> audioout.cpp:sceAudioOutOpen:304: id = 255 port_type = Main index = 0 length = 256 sample_rate = 48000 param_type = Float_8CH attr = None
[Lib.AudioOut] <Error> sdl_audio.cpp:SDLPortBackend:40: Failed to configure SDL audio stream channel map: Wrong number of channels
```
Log:
[shad_log.zip](https://github.com/user-attachments/files/18279952/shad_log.zip)

**Comment by squidbus** [comment]
Please check again.

**Comment by VasylBaran** [comment]
@squidbus I can confirm that after your changes in [this build](https://github.com/shadps4-emu/shadPS4/actions/runs/12557560930) sound works properly for me. Thank you so much! ;-)

**Comment by georgemoralis** [comment]
this seems to work fine. I am really sorry about cubeb removal only ;/

**Comment by Emulator-Team-2** [comment]
The latest commit fixes issue with missing audio.

**Comment by squidbus** [comment]
> this seems to work fine. I am really sorry about cubeb removal only ;/

The code is still in history so we can bring it back later if we need it, but I don't see a point in having it currently if there's no differences and some people report random crashes or hangs.

**Comment by sam20112011** [comment]
Well, the difference is in the volume. The sdl is much quieter compared to the cubeb.

**Comment by squidbus** [comment]
> Well, the difference is in the volume. The sdl is much quieter compared to the cubeb.

I've never noticed a difference on my system but if this is an issue it can probably be fixed for SDL.

**Comment by Hermiten** [comment]
It's an issue already reported yes

**Comment by sam20112011** [comment]
Here's a demonstration of the two sound systems https://youtu.be/6Pe7JuQOjTg
Maybe in other games, there is no difference.

**Comment by EliEron** [comment]
I've also experienced the SDL being abnormally quiet issue, and for me it affect all games.

So it's not Bloodborne specific.

**Comment by rharish101** [comment]
Just wanted to note down my experiences on PipeWire + Wayland + Arch Linux. I previously had audio issues with Bloodborne (CUSA03173) on the SDL backend, which were fixed by the cubeb backend. Now, after testing the latest main branch (i.e. after this PR was merged), there are no audio issues for me on the SDL backend.

**Comment by morten71** [comment]
I'm using gentoo linux with pulseaudio. Before this was merged I hadn't had audio troubles. When cubec was introduced, I noticed increased audio lag, but otherwise no problems.
Now most times I start Bloodborne, I have no sound, and the terminal output is filled with "audio queue backed up" messages like this:

`[Lib.AudioOut] <Warning> sdl_audio.cpp:Output:71: SDL audio queue backed up (32768 queued, 32768 threshold), clearing.`

Very rarely I do get sound, and no "audio queue backed up" lines at all. This seems to happen randomly.

This is my shad_log file:
[shad_log_a76e8f02.txt.zip](https://github.com/user-attachments/files/18285818/shad_log_a76e8f02.txt.zip)

**Pull request merged**
