### PR TITLE
GnmDriver: Clear context support

### PR DESCRIPTION
**Pull request by psucien**
This PR adds proper handling of clear state PM4 packet. Also helps with regression in https://github.com/shadps4-emu/shadPS4/pull/551

### CODE REVIEW

**Comment by bigol83** [comment]
Final Fantasy VII remaster crashes with an error i have never seen when starting a new game 

```
[Debug] <Critical> video_out.cpp:operator():272: Assertion Failed!
Out of order flip IRQ

```
Can't attack a log because with this game it reaches more than 200 Mb in size 

Red Dead Redemption crashes after logos before reaching main menu with this error 

`[Debug] <Critical> control_flow_graph.cpp:operator():26: Assertion Failed!`

[shad_log.txt](https://github.com/user-attachments/files/16738374/shad_log.txt)

**Comment by poudink** [comment]
you can zip your log if it's too big

**Comment by gandalfthewhite19890404** [comment]
> Final Fantasy VII remaster crashes with an error i have never seen when starting a new game
> 
> ```
> [Debug] <Critical> video_out.cpp:operator():272: Assertion Failed!
> Out of order flip IRQ
> ```
> 
> Can't attack a log because with this game it reaches more than 200 Mb in size
> 
> Red Dead Redemption crashes after logos before reaching main menu with this error
> 
> `[Debug] <Critical> control_flow_graph.cpp:operator():26: Assertion Failed!`
> 
> [shad_log.txt](https://github.com/user-attachments/files/16738374/shad_log.txt)

rdr - issue in main branch. Why are you report here?

**Comment by bigol83** [comment]
Red Dead Redemption reaches ingame for me with latest main build

Cattura

but it crashes with this PR, that's why i reported it

**Comment by bigol83** [comment]
With latest commit FF VII is no more slow and the log size is normal so i could check it with sync log and validation. It still crashes with the same error

[shad_log.txt](https://github.com/user-attachments/files/16739654/shad_log.txt)

**Comment by psucien** [comment]
> With latest commit FF VII is no more slow and the log size is normal so i could check it with sync log and validation. It still crashes with the same error
> 
> [shad_log.txt](https://github.com/user-attachments/files/16739654/shad_log.txt)

Thank you for checking this.
The crash is not related to the changes and seems the result of regression reported earlier: https://github.com/shadps4-emu/shadPS4/issues/409

**Comment by Emulator-Team-2** [comment]
The latest commit fixes issue: #435.
https://github.com/shadps4-emu/shadPS4/pull/567/commits/c9c86730990b54100cbcbf89e29da4cf3e4c6223

**Comment by bigol83** [comment]
Latest commit fixes Red Dead Redemption crash

**Review by raphaelthegreat — APPROVED** [review]

**Pull request merged**
