### PR TITLE
Cheats/Patches

### PR DESCRIPTION
**Pull request by DanielSvoboda**
### Add Support for `Cheats and Patches`

This PR adds the ability to apply cheats and patches to the emulator. Below are two explanations: one simplified and one with technical details for developers.

---

**Cheats**  
Right-click on a game and select the 'Cheats/Patches' option. From there, you can download cheats from three repositories: wolf2022, GoldHEN, and shadPS4. If a cheat is available in more than one repository, you can delete the undesired file using a specific button. Cheats will only be downloaded for the specific serial and version of the installed game and will be renamed with the format serial+version+repository.

In the top menu, under "Settings -> Utils -> Download Cheats/Patches", you can download all cheats at once for the installed games. It is recommended to apply cheats only during gameplay.

**Patches**  
In addition to cheats, you can also download patches. Unlike cheats, patches are downloaded for all games, not just one specific game. The patch file is quite small. Right-click on a game, select 'Cheats/Patches', go to the patches tab, check the patches you want to use, and click 'Save'. This ensures that these options will be applied automatically every time the emulator is started, without needing to reopen the panel. In the Patches tab, if you hover over them you can see the description on the left side.

image

image

---

**Technical Explanation:**

For developers who will maintain this code in the future:

1. **Cheats**  
   - Cheats are downloaded from repositories and stored in the `user\cheats\` folder, with names in the format serial+version+repository. Some repositories may provide multiple files for the same serial+version, distinguished by suffixes like _2 or _3, indicating different authors. The emulator can read any file starting with serial+version, for example:
     ```
     CUSA07023_01.03_TEST_shadPS4.json
     CUSA07023_01.03_GoldHEN.json
     CUSA07023_01.03_DANIEL.json
     ```
   - Cheats in JSON with `hint:null` are treated as absolute addresses. If the tag is missing, they are considered relative. The emulator handles these cases correctly.

2. **Patches**  
   - Patches are downloaded to `user\patches\repository_name`. After downloading the .xml files, a `files.json` file is created to map the files to the selected games, as patches are not named as systematically as cheats. The `files.json` includes information about the 'serial and version', ensuring that only the patch corresponding to the game's version is shown. Patches may also include a 'mask', with the title " (any version)".

   - In the context menu (right-click), select the patches you want to activate and save the settings. These patches will be automatically applied every time the game is started in QT mode; patches are not applied in SDL mode. The support for various types present in the XML is provided: byte, bytes16, bytes32, bytes64, bytes, float32, float64, utf8, utf16, mask, mask_jump32.

   - The 'mask' functionality is still under testing, as there are currently few games using it.
   - Changes are made in eboot.bin, not tested with changes in .elf
   - I found some of the text too long to translate in parts,
so I replaced it with the text below, so the text only appears in the .ts translation file:
defaultTextEdit_MSG
CheatsNotFound_MSG
CheatsDownloadedSuccessfully_MSG
DownloadComplete_MSG

**Repository for New Cheats/Patches**  
New cheats and patches can be added via the repository:  
[https://github.com/shadps4-emu/ps4_cheats](https://github.com/shadps4-emu/ps4_cheats)

Interface based on [issues/372 ](https://github.com/shadps4-emu/shadPS4/issues/372)

- [X] Front-end - Interface
- [X] Back-end - Apply the Cheats/Patchs  modifications - By: CrazyBloo 
- [x] Plus other corrections that are not worth describing in detail...

Authored-by: DanielSvoboda
Co-authored-by: CrazyBloo

### CODE REVIEW

**Comment by gorshco** [comment]
An amazing idea! Are you planning to add patches as well (https://github.com/GoldHEN/GoldHEN_Patch_Repository)?
This is where the "60FPS/Uncap FPS" patches reside.

**Comment by DanielSvoboda** [comment]
I forgot to do the patches part haha, I'm glad you said it, I had only added the cheats, at the moment I don't have time, but it should be added

**Comment by georgemoralis** [comment]
hmm all that window code , shouldn't be better to be on a separate cpp/h file? It will be more clean and it can be also be able to open it from different places (e.g menu)

**Comment by Curioso9998** [comment]
it's a shame it seems that the cheats and patches only download for european versions games

**Comment by DanielSvoboda** [comment]
@Curioso9998 It only downloads for the version that is available, the combination of serial + version, maybe the version or serial you have does not have cheats available.
And just remembering that at this moment it is not yet possible to apply the modifications, we will have them soon...

**Comment by georgemoralis** [comment]
which repo should i fork to shadps4 org?

**Comment by georgemoralis** [comment]
i wonder if it a good idea , since some patches - cheats not working or might not work probably to create a repo with the proper format and we can have pr's with valid patches (patches that has been tested). We can also have an checkbox somewhere to choose from where to download (golden repo or our own repo) until we get our repo filled with significant number of patches - cheats

**Comment by DanielSvoboda** [comment]
And that's the end 🤠

**Pull request merged**
