### PR TITLE
Fixed false-positive image reuploads

### PR DESCRIPTION
**Pull request by roamic**
Should fix half of the rainbow artifacts in BloodBorne.
Big thanks to @raphaelthegreat and @psucien for helping debug and fix this.

### CODE REVIEW

**Comment by Missake212** [comment]
tried a full run in central yharnam, it is greatly reduced but I still got one (and it's way more purple than it used to be, also got it on one broken crate) great work !
Capture d'écran 2024-11-20 202650
Capture d'écran 2024-11-20 203833

**Comment by AwesomeSoftware79** [comment]
Improved a lot, but still a couple of rainbow effects here and there (once in about 45 min.)-

image

**Comment by GHU7924** [comment]
I made a circle in Central Yharnam, and during that time I had only one moment:


Edit: If something needs to be entered in the Log Filter, then write it, I will test it later if necessary.

**Comment by TagoSMD** [comment]
NOPE
less frequent but still happen

**Comment by roamic** [comment]
This fixes half of false-positive image re-uploads. The one we can easily detect. The other half is a lot more complicated to spot so will be out of scope of this PR.

**Comment by Foul-Tarnished** [comment]
Will this get merged soon ?

I wonder if #1451 helps with the remaining buggy textures 🤔

**Comment by roamic** [comment]
The latest commit should solve remaining issues in a non-hacky way.

**Comment by rafael-57** [comment]
Thank you! Did some rounds of testing with Bloodborne in an heavy area that would produce rainbow corruptions after hitting enemies very fast, haven't seen any so far. If this doesn't regress other games I would merge soon 👍

**Comment by Missake212** [comment]
Tested through Central Yharnam, killed every enemies like I did last time, not a single rainbow, will try a few more runs but usually I get at least 1, this is amazing work !

**Comment by ZuwasieMan** [comment]
Played about ca. 45 minutes, I could not find any rainbow/metallic/grey textures. Looks very good.

**Comment by ZuwasieMan** [comment]
After one hour I found one metallic/grey texture:

grafik

**Comment by AxeKeeper** [comment]
Скриншот 24-11-2024 233426
Скриншот 24-11-2024 233440
Скриншот 24-11-2024 233523

**Comment by Missake212** [comment]
Couldn't capture it since it was quick but while hitting an enemy he turned rainbow for a second until I hit him again, beside that didn't see any other rainbows

**Comment by roamic** [comment]
> Couldn't capture it since it was quick but while hitting an enemy he turned rainbow for a second until I hit him again, beside that didn't see any other rainbows

I've seen this too, thought I fixed it with hash initialization. Seems not.

**Comment by sam20112011** [comment]
> Скриншот 24-11-2024 233426 Скриншот 24-11-2024 233440 Скриншот 24-11-2024 233523

This has been going on for quite some time. Even before the blackness/rainbow fix and with mod from Nexus fix. It's just very rare and hard to pay attention to.

By the way, the rainbow effect on enemies, happens even in the version with the hack. Short. But still.
Perhaps it is really something to do with texture cache overflow, or 2gb buffer bug. Since it happens after a long gaming session.

**Comment by Missake212** [comment]
Killed everyone in Central Yharnam like usual, not a single rainbow, this might be the one, I'll try a few more times to make sure but it's looking good !

**Pull request merged**
