### PR TITLE
qt_gui: Added stopping games by escape key or stop button

### PR DESCRIPTION
**Pull request by ElBread3**
This PR should theoretically add stopping games by either pressing escape or the stop button in the main window. This is implemented by creating a SDL window manager that's only current use is to hold a function that simply sends a quit event in order to close the window (less invasive than adding SDL headers into QT classes, also can be expanded in the future). It is important to note that currently the emulator doesn't seem to have any de-initialization functions which would need to be implemented so that exiting isn't basically a crash.

### CODE REVIEW

**Comment by DeveloperVaibhav1** [comment]
try an alternative method for this .

**Comment by DeveloperVaibhav1** [comment]
> This PR should theoretically add stopping games by either pressing escape or the stop button in the main window. This is implemented by creating a SDL window manager that's only current use is to hold a function that simply sends a quit event in order to close the window (less invasive than adding SDL headers into QT classes, also can be expanded in the future). It is important to note that currently the emulator doesn't seem to have any de-initialization functions which would need to be implemented so that exiting isn't basically a crash.
Its simply awesome

**Comment by DeveloperVaibhav1** [comment]
fix it for clang format

**Comment by DeveloperVaibhav1** [comment]
how to access the source code

**Comment by ElBread3** [comment]
Closing as this is now old and will need to find a better way to do this in a more integrated fashion

**Pull request closed without merging**
