### PR TITLE
video_core: Bloodborne stabilization pt1

### PR DESCRIPTION
**Pull request by raphaelthegreat**
Implements some missing features in shader recompiler. When this is merged we wont have to skip any graphics shaders anymore (for compute it's still needed due to usage of DS_APPEND)

Most sharp related crashes were in shaders that used a specific pattern of preserving SGPRs. Because these registers are much fewer than VGPRs the compiler might choose to broadcast them to certain scratch VGPRs of specific lanes with V_WRITELANE_B32. When they are needed V_READLANE_B32 is used to read them back. The pattern is as follows:

```
/*00000000001c*/ s_load_dwordx8  s[16:23], s[14:15], 0x20
/*000000000024*/ v_writelane_b32 v3, s16, 2
/*000000000028*/ v_writelane_b32 v3, s17, 3
/*00000000002c*/ v_writelane_b32 v3, s18, 4
/*000000000030*/ v_writelane_b32 v3, s19, 5
...
/*000000000780*/ v_readlane_b32  s28, v3, 2
/*000000000784*/ v_readlane_b32  s29, v3, 3
/*000000000788*/ v_readlane_b32  s30, v3, 4
/*00000000078c*/ v_readlane_b32  s31, v3, 5
/*000000000790*/ s_buffer_load_dwordx4 s[28:31], s[28:31], 0x4c
```
Our writelane stub proved to be wrong here, since it would overwrite the VGPR completely, making all previous lane writes invisible. To fix this, dedicated IR instructions for ReadLane and WriteLane have been added. The WriteLane IR op interface is based on WriteInvocationAMD added in SPV_AMD_shader_ballot. A constant propagation pass has been added which detects ReadLane instructions whose value comes directly from a WriteLane (no operations that modify the VGPR in between) and eliminates it with the actual SSA value. This allows the resource tracking pass to work properly and fix invalid trackings.

Also implemented image derivatives specifically for 2D images (supporting more than that is a bit tricky, for later ig).

### CODE REVIEW

**Comment by rafael-57** [comment]
EDIT: Best to just use git to merge BB-Hacks into BB-Stable locally if you know how to, to avoid mistakes during copy-paste.

Thank you!!!

I confirmed with @georgemoralis on discord that in order to test Bloodborne with this we will need to:

1. Download BB-Stable source code
2. Manually copy and paste the changes that are in BB-Hacks, locally into the BB-Stable source we downloaded
3. Build and test

Will do in the afternoon as soon as I'm off work.

**Comment by raphaelthegreat** [comment]
You need to cherry pick the changes, git doesn't work by copy pasting files and there are overlapping changes here with bb hacks

**Comment by rafael-57** [comment]
> You need to cherry pick the changes, git doesn't work by copy pasting files and there are overlapping changes here with bb hacks

Yes I was unclear, I meant copy and paste the changes in the code, not whole files.

**Comment by raphaelthegreat** [comment]
Yes that's fine. Cherry pick is that but a lot faster

**Comment by rafael-57** [comment]
Character outline is now working again for me! It's been so long! And...it actually went ingame!!! It crashed so fast I wasn't able to screen.

P.S. I just downloaded this latest action and tested. No manual build or merge with bb-hacks.

image
image

[shad_log.txt](https://github.com/user-attachments/files/16732311/shad_log.txt)

**Comment by Hashdog123** [comment]
testing with just the action itself, i've gotten the same liverpool graphics error both on new game and loading a game. 
it does this right before going ingame as i can see the loading screen start to fade before this error
unlike rafael above me, i have not been able to reproduce a character outline with the same action

[shad_log.txt](https://github.com/user-attachments/files/16735978/shad_log.txt)

**Comment by Hashdog123** [comment]
> testing with just the action itself, i've gotten the same liverpool graphics error both on new game and loading a game. it does this right before going ingame as i can see the loading screen start to fade before this error unlike rafael above me, i have not been able to reproduce a character outline with the same action
> 
> [shad_log.txt](https://github.com/user-attachments/files/16735978/shad_log.txt)

another thing to add is that, when continuing a save, i get the error immediately

**Comment by SuperPlasmaPanda** [comment]
DSR seems to have some interesting colors as of this PR,

3sHnzwB
gK44Hh1

Loading the save file on new boot seems to fix the surrounding geometry colors, but effect reappears on character and enemies when approaching Undead Burg.


https://github.com/user-attachments/assets/386cf2bd-1e75-40ad-81d9-544ff299326f



[shad_log DSR firelink to undead burg crash.txt](https://github.com/user-attachments/files/16736034/shad_log.DSR.firelink.to.undead.burg.crash.txt)


I'm able to produce the character outline in BB incredibly inconsistently. It seems to show up and go away after leaving and trying again at random. The Paleblood cutscene will also randomly choose to hang for a minute or two when I was testing this.


https://github.com/user-attachments/assets/dcb596c5-5e98-4c2e-9478-797032741efc



[shad_log BB crash on skipping new game cutscene.txt](https://github.com/user-attachments/files/16735988/shad_log.BB.crash.on.skipping.new.game.cutscene.txt)
[shad_log BB crash on waiting for cutscene, then loading after character create.txt](https://github.com/user-attachments/files/16735989/shad_log.BB.crash.on.waiting.for.cutscene.then.loading.after.character.create.txt)
[shad_log BB loading new game.txt](https://github.com/user-attachments/files/16735990/shad_log.BB.loading.new.game.txt)
[shad_log BB loading save in Hunters Dream.txt](https://github.com/user-attachments/files/16735991/shad_log.BB.loading.save.in.Hunters.Dream.txt)
[shad_log BB crash after trying to get char outline to show up, then loading in after getting it.txt](https://github.com/user-attachments/files/16736008/shad_log.BB.crash.after.trying.to.get.char.outline.to.show.up.then.loading.in.after.getting.it.txt)

Let me know if there's a better format for me to post in, thank you again for the good work.

**Pull request merged**
