### PR TITLE
savedata: Handle a missing case in saveDataMount

### PR DESCRIPTION
**Pull request by Exhigh**
This should potentially fix the mount issue in Resistance : Retribution (CUSA32636)

Testing is welcome.

### CODE REVIEW

**Comment by Exhigh** [comment]
Once the fix is confirmed to fix the issue in CUSA32636, this PR should be ready for review.

**Comment by greggameplayer** [comment]
@Exhigh thanks for the fix, i test it this evening and i will tell the result here

**Comment by greggameplayer** [comment]
it seems to progress further and error here : 
image

here the log : 
[shad_log.txt](https://github.com/user-attachments/files/16826014/shad_log.txt)

i try to pass that point as soon as i hit continue it keeps throwing that error but it writes a new line in the log of stub : 
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRazorCpuPlotValue (nid: njGikRrxkC0) called

**Comment by greggameplayer** [comment]
i don't know if it's really related to libSceRazorCpu because it seems to be a library use only for application debugging purposes for developers

**Comment by lzardy** [comment]
> i don't know if it's really related to libSceRazorCpu because it seems to be a library use only for application debugging purposes for developers

Yes it is likely a game functionality is not behaving correctly and the game attempts to debug it.

**Pull request merged**
