### PR TITLE
savedata: Add another missed case in saveDataMount

### PR DESCRIPTION
**Pull request by Exhigh**
This should potentially fix Deadpool (CUSA03528) #554.

Testing is appreciated.

### CODE REVIEW

**Comment by Exhigh** [comment]
Once the fix is confirmed to fix the issue in CUSA03528, this PR should be ready for review.

**Comment by EmulationChannel** [comment]
Yes fixed Deadpool (CUSA03528)  in boot game some logs file
[shad_log.txt](https://github.com/user-attachments/files/16780682/shad_log.txt)
I took advantage and took the AC BLACK FLAG test
[shad_log.txt](https://github.com/user-attachments/files/16780719/shad_log.txt)

**Comment by greggameplayer** [comment]
This mount mode 58 is also needed for Resistance : Retribution (CUSA32636), i haven't tested your modification on it yet.

**Comment by Exhigh** [comment]
Mount mode 58 has already been implemented. Try booting the game and check again with a latest WIP build to confirm.
@greggameplayer

**Comment by greggameplayer** [comment]
@Exhigh my bad it's 48 that is needed : 
image

**Pull request merged**
