### PR TITLE
gui: Implement settings dialog

### PR DESCRIPTION
**Pull request by dima-xd**
As simple as it can be, without any abstraction and etc.

Example:
image

### CODE REVIEW

**Comment by Xphalnos** [comment]
This is incredible progress!
Only one thing would be necessary: ​​remove the Save button. I think it's better to have a button that does both.

**Comment by dima-xd** [comment]
> This is incredible progress! Only one thing would be necessary: ​​remove the Save button. I think it's better to have a button that does both.

Not sure about that.  For me it's not that necessary. Let's see what others say

**Comment by ryzendew** [comment]
can you add 1 last thing ? to disable logs but have it on by default

**Comment by dima-xd** [comment]
> can you add 1 last thing ? to disable logs but have it on by default

I don't want to add new functionalities in this PR. Maybe me or someone else will add it after this PR

**Pull request merged**
