### PR TITLE
ru_RU translation fixes 2

### PR DESCRIPTION
**Pull request by f1amy**
Fixes latest new translations for ru_RU

### CODE REVIEW

**Comment by f1amy** [comment]
reuse check fail seem to be not related to PR
```
ERROR: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Afsfe%2Freuse%3Apull&service=registry.docker.io: 401 Unauthorized
```

**Comment by DanielSvoboda** [comment]
> reuse check fail seem to be not related to PR
> 
> ```
> ERROR: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Afsfe%2Freuse%3Apull&service=registry.docker.io: 401 Unauthorized
> ```

I think this was just some github bug, @georgemoralis  can you run 'Re-run all jobs' ? I think it should solve

**Comment by f1amy** [comment]
Will rebase

**Comment by f1amy** [comment]
Ready for review, thankfully github has let me pass checks this time

**Pull request merged**
