### PR TITLE
cmake: unbundle libpng

### PR DESCRIPTION
**Pull request by abouvier**
`zlib-ng` is not used anymore (apart from building `zlib`) and could be replaced by `zlib` repo directly.

### CODE REVIEW

**Comment by georgemoralis** [comment]
not actually , zlib-ng is being used in compatibility mode , that means that the syntax is the same as zlib so you don't have to rewrite code , but optimizations is still from zlib-ng

**Comment by abouvier** [comment]
It's good then, `zlib`/`zlib-ng-compat` from the system (depending on user configuration) will be used OR `zlib-ng-compat` from externals will be built.

**Comment by raphaelthegreat** [comment]
People seem to have trouble building on windows after this

**Comment by abouvier** [comment]
Well, a full cmake error output would be helpful :p

**Comment by AboMedoz** [comment]
> Well, a full cmake error output would be helpful :p

```
'externals/zlib-ng/zlibstatic-ngd', needed by 'shadps4.exe', missing and no known rule to make it    
```

**Comment by abouvier** [comment]
> ```
> 'externals/zlib-ng/zlibstatic-ngd', needed by 'shadps4.exe', missing and no known rule to make it    
> ```
This is not really what I would call a full report.

**Comment by AboMedoz** [comment]
> > ```
> > 'externals/zlib-ng/zlibstatic-ngd', needed by 'shadps4.exe', missing and no known rule to make it    
> > ```
> 
> This is not really what I would call a full report.

that's what i get build doesn't even start

**Comment by MajorP93** [comment]
```
FAILED: externals/libpng/pnglibconf.out D:/a/shadPS4/shadPS4/build/externals/libpng/pnglibconf.out 
C:\Windows\system32\cmd.exe /C "cd /D D:\a\shadPS4\shadPS4\build\externals\libpng && "C:\Program Files\CMake\bin\cmake.exe" -DINPUT=D:/a/shadPS4/shadPS4/build/externals/libpng/pnglibconf.c -DOUTPUT=D:/a/shadPS4/shadPS4/build/externals/libpng/pnglibconf.out -P D:/a/shadPS4/shadPS4/build/externals/libpng/scripts/cmake/genout.cmake"
D:/a/shadPS4/shadPS4/build/externals/libpng/pnglibconf.c(34,11): fatal error: 'zlib.h' file not found

   34 | # include <zlib.h>

      |           ^~~~~~~~

1 error generated.

CMake Error at scripts/cmake/genout.cmake:87 (message):
  Failed to generate
  D:/a/shadPS4/shadPS4/build/externals/libpng/pnglibconf.out.tf1


[4/722] Building C object _deps\zlib-build\CMakeFiles\zlib.dir\arch\generic\adler32_c.c.obj
[5/722] Building CXX object src\imgui\renderer\CMakeFiles\Dear_ImGui_FontEmbed.dir\__\__\__\externals\dear_imgui\misc\fonts\binary_to_compressed_c.cpp.obj
D:\a\shadPS4\shadPS4\externals\dear_imgui\misc\fonts\binary_to_compressed_c.cpp(23,9): warning: '_CRT_SECURE_NO_WARNINGS' macro redefined [-Wmacro-redefined]
   23 | #define _CRT_SECURE_NO_WARNINGS
      |         ^
<command line>(9,9): note: previous definition is here
    9 | #define _CRT_SECURE_NO_WARNINGS 1
      |         ^
1 warning generated.
[6/722] Building CXX object externals\glslang\glslang\CMakeFiles\glslang.dir\cmake_pch.cxx.obj
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.
```

**Comment by abouvier** [comment]
You should really post the full output, including the cmake configuration phase.

**Comment by MajorP93** [comment]
> You should really post the full output, including the cmake configuration phase.

[zlib_error.txt](https://github.com/user-attachments/files/17967616/zlib_error.txt)

**Comment by abouvier** [comment]
Can you try to add `get_target_property(ZLIB_INCLUDE_DIRS zlib INTERFACE_INCLUDE_DIRECTORIES)` after the line `add_library(ZLIB::ZLIB ALIAS zlib)` in `externals/CMakeLists.txt`?

**Comment by viniciuslrangel** [comment]
@abouvier Still having issues here.

Configuration: [configure.txt](https://github.com/user-attachments/files/17969623/configure.txt)

Build:
```
"cmake.exe" --build \shadPS4\cmake-build-debug-clang_vs_x64 --target shadps4 -j 30
[1/267] C:\WINDOWS\system32\cmd.exe /C "cd /D \shadPS4\cmake-build-debug-clang_vs_x64\externals\discord-rpc && "clang-format.exe" -i -style=file -fallback-style=none /shadPS4/externals/discord-rpc/examples/send-presence/send-presence.c /shadPS4/externals/discord-rpc/examples/unrealstatus/Plugins/discordrpc/Source/DiscordRpc/Private/DiscordRpc.cpp /shadPS4/externals/discord-rpc/examples/unrealstatus/Plugins/discordrpc/Source/DiscordRpc/Private/DiscordRpcBlueprint.cpp /shadPS4/externals/discord-rpc/examples/unrealstatus/Plugins/discordrpc/Source/DiscordRpc/Private/DiscordRpcPrivatePCH.h /shadPS4/externals/discord-rpc/examples/unrealstatus/Plugins/discordrpc/Source/DiscordRpc/Public/DiscordRpc.h /shadPS4/externals/discord-rpc/examples/unrealstatus/Plugins/discordrpc/Source/DiscordRpc/Public/DiscordRpcBlueprint.h /shadPS4/externals/discord-rpc/examples/unrealstatus/Source/unrealstatus/unrealstatus.cpp /shadPS4/externals/discord-rpc/examples/unrealstatus/Source/unrealstatus/unrealstatus.h /shadPS4/externals/discord-rpc/examples/unrealstatus/Source/unrealstatus/unrealstatusGameModeBase.cpp /shadPS4/externals/discord-rpc/examples/unrealstatus/Source/unrealstatus/unrealstatusGameModeBase.h /shadPS4/externals/discord-rpc/include/discord_register.h /shadPS4/externals/discord-rpc/include/discord_rpc.h /shadPS4/externals/discord-rpc/src/backoff.h /shadPS4/externals/discord-rpc/src/connection.h /shadPS4/externals/discord-rpc/src/connection_unix.cpp /shadPS4/externals/discord-rpc/src/connection_win.cpp /shadPS4/externals/discord-rpc/src/discord_register_linux.cpp /shadPS4/externals/discord-rpc/src/discord_register_win.cpp /shadPS4/externals/discord-rpc/src/discord_rpc.cpp /shadPS4/externals/discord-rpc/src/dllmain.cpp /shadPS4/externals/discord-rpc/src/msg_queue.h /shadPS4/externals/discord-rpc/src/rpc_connection.cpp /shadPS4/externals/discord-rpc/src/rpc_connection.h /shadPS4/externals/discord-rpc/src/serialization.cpp /shadPS4/externals/discord-rpc/src/serialization.h"
[2/267] Generating pnglibconf.out
FAILED: externals/libpng/pnglibconf.out /shadPS4/cmake-build-debug-clang_vs_x64/externals/libpng/pnglibconf.out 
C:\WINDOWS\system32\cmd.exe /C "cd /D \shadPS4\cmake-build-debug-clang_vs_x64\externals\libpng && "cmake.exe" -DINPUT=/shadPS4/cmake-build-debug-clang_vs_x64/externals/libpng/pnglibconf.c -DOUTPUT=/shadPS4/cmake-build-debug-clang_vs_x64/externals/libpng/pnglibconf.out -P /shadPS4/cmake-build-debug-clang_vs_x64/externals/libpng/scripts/cmake/genout.cmake"
/shadPS4/cmake-build-debug-clang_vs_x64/externals/libpng/pnglibconf.c(34,11): fatal error: 'zlib.h' file not found
   34 | # include <zlib.h>
      |           ^~~~~~~~
1 error generated.
CMake Error at scripts/cmake/genout.cmake:87 (message):
  Failed to generate
  /shadPS4/cmake-build-debug-clang_vs_x64/externals/libpng/pnglibconf.out.tf1


[3/267] Linking CXX static library externals\discord-rpc\src\discord-rpc.lib
ninja: build stopped: subcommand failed.
```

**Comment by Foul-Tarnished** [comment]
Still getting this...
@abouvier 
image

Just did a full git clone --recursive
then opened in VS 2022

The last error line appeared when I added Qt through CMake argument list, and is probably unrelated

**Pull request merged**
