### PR TITLE
Optimize initialize UserPaths reserve count known paths

### PR DESCRIPTION
**Pull request by GermanAizek**
I think it will be useful for faster init emulator

### CODE REVIEW

**Comment by georgemoralis** [comment]
Probably faster but I think someone can easy forget to update it when adding new folder so it might be risky

**Comment by GermanAizek** [comment]
> Probably faster but I think someone can easy forget to update it when adding new folder so it might be risky

@georgemoralis is there way to make unordered_map initially already initialized? For example, like consteval or constexpr, such solution is better than reserve. Alternatively, I can get count iterations through for loop and reserve it. Tell me what is the best way to do this.

**Comment by raphaelthegreat** [comment]
I don't think this is needed. Calling reserve is nice but when you are adding it to these initialization paths it doesn't benefit much and just adds more lines of code

**Comment by georgemoralis** [comment]
close as not needed

**Pull request closed without merging**
