### PR TITLE
Patch CPUID

### PR DESCRIPTION
**Pull request by OFFTKP**
Untested and WIP since DS crashes for some unrelated reason

### CODE REVIEW

**Comment by korenkonder** [comment]
There's a better way of doing this. You can relocate instructions after that too

**Comment by OFFTKP** [comment]
~~Needs to be reworked to instead patch it normally and copy the instruction at the end of the injected code since the trampoline jump is bigger than 2 bytes for cpuid~~

Nevermind, after some discussion it's not as easy as it sounds, because the next instruction may be a relative jump or some other code might want to jump to the instruction after cpuid that would get clobbered.

**Comment by bigol83** [comment]
Tested with Windows, it doesn't crash for me, but Dark Souls still has the same issue of exploding geometry when moving the character

Cattura

**Comment by OFFTKP** [comment]
No matter the combination of values returned the dark souls problem is not fixed so I am going to retire this PR, the method to patch the CPUID was pretty neat I think so maybe it can be useful in the future

**Pull request closed without merging**
