### PR TITLE
Device file abstraction & Mouse hid implementation

### PR DESCRIPTION
**Pull request by viniciuslrangel**
Also steering wheel emulation (~???~)

### CODE REVIEW

**Comment by georgemoralis** [comment]
looking promising

**Comment by georgemoralis** [comment]
for tests : you need libSceMouse.sprx on sys_modules folder  . Testing games should be ones that spams sceMouseRead on log

**Comment by volcanonn** [comment]
TRANSFORMERS: Devastation crashes when it askes to use mouse
[shad_log.txt](https://github.com/user-attachments/files/17744345/shad_log.txt)

**Comment by kalaposfos13** [comment]
NieR: Automata doesn't even boot with this, on main it would show the splash screen, and crash before the main menu.
I tried it with and without libSceMouse, and even merging it with more-kernel, but every try just crashes here:
[shad_log.txt](https://github.com/user-attachments/files/17778708/shad_log.txt)
On the libMouse branch, the game boots and asks for the mouse, and with more-kernel added, even reaches menus, but the mouse was unresponsive there.

**Comment by viniciuslrangel** [comment]
Replaced by #1577

**Pull request closed without merging**
