### PR TITLE
style: add Tokyo Night theme

### PR DESCRIPTION
**Pull request by tomboylover93**
Based on [lospec/palette-list/tokyo-night](https://lospec.com/palette-list/tokyo-night) and [folke/tokyonight.nvim](https://github.com/folke/tokyonight.nvim).

Screenshot_20241217_103906

### CODE REVIEW

**Comment by abouvier** [comment]
Wouldn't it be better to remove all theme related stuff in shadps4 and configure your preferred Qt theme on your system?

**Comment by tomboylover93** [comment]
I wanted to do exactly that, and as a matter of fact I'm making a "System" theme which uses the colors of the Qt theme in your system, but that's only for dark themes and I haven't figured out how to apply the system colors when the "System" theme is selected (I have to select it, close shadPS4 and reopen it for it to work). If I do get it working properly I'll make a pull request for that.

**Comment by tomboylover93** [comment]
Forgot to make a separate pull request for that last commit. I would like for a maintainer to revert that and only include the Tokyo Night theme.

**Comment by Hermiten** [comment]
So what about this theme ? Is it ready for now ?
Because there is this in the same time: https://github.com/shadps4-emu/shadPS4/pull/1828

**Comment by tomboylover93** [comment]
This one is ready to be merged. That other PR was already ready to be merged when I made it but I turned it into a draft because I need to figure out issues with the system theme on Windows.

**Comment by Hermiten** [comment]
Ok perfect, some things have been done in the GUI, maybe a last rebase before pushing it ?

**Comment by tomboylover93** [comment]
Done.

**Pull request merged**
