### PR TITLE
Qt-GUI: Improvements (Part 2)

### PR DESCRIPTION
**Pull request by Xphalnos**
Before:
image

After:
image

### CODE REVIEW

**Comment by raphaelthegreat** [comment]
Could we make the settings window a bit smaller, feel like there is a lot of empty space

**Comment by Xphalnos** [comment]
Done!

Preview with Qt Creator:
image

**Comment by Xphalnos** [comment]
image

**Comment by georgemoralis** [comment]
Logger options seems stretched and occupied a lot of space

**Comment by ryzendew** [comment]
> image

try adding logging to it's own tab or move it to debug

**Comment by Xphalnos** [comment]
> try adding logging to it's own tab or move it to debug

I'm not sure it's a good idea to do it now because at the moment the options menu is quite empty.

**Comment by AussiePlick** [comment]
Eventually you will need to add **manually add game updates**.  I have a jail broken PS4 Pro and when I download the games and updates from it, the update PKG are already extracted, so I cant update the games to newer versions.
Also, the ability to **add DLC**.
Sorry if I shouldn't add this here, but it will help you in future layout of GUI.

**Comment by Xphalnos** [comment]
> Eventually you will need to add **manually add game updates**. I have a jail broken PS4 Pro and when I download the games and updates from it, the update PKG are already extracted, so I cant update the games to newer versions. Also, the ability to **add DLC**. Sorry if I shouldn't add this here, but it will help you in future layout of GUI.

For the moment it is not possible to install DLC and for updates, you can do it via "Install Packages (PKG)"

**Comment by Xphalnos** [comment]
> Logger options seems stretched and occupied a lot of space

Is it good now?
image

**Pull request merged**
