### PR TITLE
Updated BatchMap2 to Handle ORBIS_KERNEL_MAP_OP_TYPE_PROTECT

### PR DESCRIPTION
**Pull request by menaman123**
* Implemented MProtect in memory.cpp that uses Protect function in address_space.cpp
* Implemented sceKernelMprotect in order for BatchMap2 to handle  ORBIS_KERNEL_MAP_OP_TYPE_PROTECT

### CODE REVIEW

**Comment by georgemoralis** [comment]
do you have any reference game?

**Comment by menaman123** [comment]
> do you have any reference game?

Yes I was using Crash N Sane trilogy (CUSA07402)

**Comment by StevenMiller123** [comment]
If fpPS4 is anything to go by, aren't sceKernelMprotect and sceKernelMtypeprotect two different functions? They use Mprotect for operation 2, and Mtypeprotect for operation 4.

**Comment by menaman123** [comment]
> If fpPS4 is anything to go by, aren't sceKernelMprotect and sceKernelMtypeprotect two different functions? They use Mprotect for operation 2, and Mtypeprotect for operation 4.

Yup i just noticed, i will make those changes. I have a question. Looking at fpPS4 i see one of the parameters is mtype. What is the equivalent in shadPS4. I know prot is the MemoryProt

**Comment by StevenMiller123** [comment]
Also, as a tester, I've found that your Mprotect implementation doesn't improve any games that crash on it (after adding Mprotect to the libkernel symbols). I tried a game that uses BatchMap op 4 as well (Crash Team Racing Nitro Fueled), and that doesn't progress any further than when removing the unimplemented line in the BatchMap function. As for your question, I'm not familiar enough with the shadPS4 source to give a clear answer.

**Comment by menaman123** [comment]
Okay so i added MTypeprotect to it and just changed MProtect to ORBIS_KERNEL_MAP_OP_PROTECT

**Comment by menaman123** [comment]
It seems like it calls the BatchMap2 function over and over again with the op 4 then it crashes. Not sure how to move pass this if anyone has any ideas.

**Comment by red-prig** [comment]
mtype -> MemoryTypes

**Pull request closed without merging**
