### PR TITLE
Handle IT_SET_QUEUE_REG and IT_SET_PREDICATION PM4 packets

### PR DESCRIPTION
**Pull request by mikusp**

### CODE REVIEW

**Comment by dbz400** [comment]
Will test out with CUSA00008 - KILLZONE™ SHADOW FALL which hits PM4 type 3 0x20 

[Debug] liverpool.cpp:ProcessGraphics:550: Unreachable code!
Unknown PM4 type 3 opcode 0x20 with count 2

**Comment by LlysiX** [comment]
Tested on rock band 4 (1.08), which previously errored out on SetPredication

Before: Crash on title screen, `Unknown PM4 type 3 opcode 0x20 with count 2`
After: Works
image

**Comment by smiRaphi** [comment]
Tested with CUSA19264 - Yo Kai Watch 4 and it crashes with this error, I don't know if this is caused by this addition or if it's just something after the pm4 type 3 error

```log
[Debug] <Critical> decode.cpp:operator():264: Assertion Failed!
Instruction format table incomplete for opcode  (13, encoding = )
```
[shad_log.txt](https://github.com/user-attachments/files/17267562/shad_log.txt)

**Comment by Rarecreature** [comment]
i dont know if this useful or not but CUSA01715 God of War® III Remastered now it crashes with this error

[Debug] <Critical> liverpool.cpp:ProcessGraphics:641: Unreachable code!
Unknown PM4 type 3 opcode 0x20 with count 2

[shad_log.txt](https://github.com/user-attachments/files/17873711/shad_log.txt)

**Comment by polybiusproxy** [comment]
Closing since these are stubs instead of implementations

**Pull request closed without merging**
