### PR TITLE
Improve sceSystemServiceReceiveEvent stub

### PR DESCRIPTION
**Pull request by StevenMiller123**
I've added both an EventType enum, and what should be the proper event struct, both based primarily off fpPS4 implementations. In the one game I've seen calling this function, the game runs a while loop until ReceiveEvent returns something other than 0, causing an infinite loop with the current implementation. 

This needs testing with other games that can call this function, as I would assume some games may regress from the error return. If any regressions are found, please provide a log. 

Confirmed improvements:
- Ghost of Tsushima
- Stranger of Paradise Final Fantasy Origin
- Hatsune Miku Project Diva X

### CODE REVIEW

**Comment by gandalfthewhite19890404** [comment]
Adventures of Fat Princess uses this

**Comment by gandalfthewhite19890404** [comment]
Sorry, Ghost of Tsushima uses this

**Comment by gandalfthewhite19890404** [comment]
Now GoTs goes further
image

**Comment by StevenMiller123** [comment]
@gandalfthewhite19890404 Could you provide a log? I've got the method set to log some extra details, so a log will tell me if there's anything the game is hardcoded to expect.

**Comment by gandalfthewhite19890404** [comment]
@StevenMiller123 
[shad_log.txt](https://github.com/user-attachments/files/17077367/shad_log.txt)

**Comment by StevenMiller123** [comment]
Thanks, looks like my stub is working as expected in Ghost of Tsushima.

**Comment by dbz400** [comment]
Stranger of Paradise: Final Fantasy Origin also uses it and it now goes in-game graphic

**Review by polybiusproxy — APPROVED** [review]

**Pull request merged**
