### PR TITLE
Creating a better Readme

### PR DESCRIPTION
**Pull request by Xphalnos**
The new readme: https://github.com/Xphalnos/shadPS4/blob/main/README.md

Always ready for modifications !

### CODE REVIEW

**Comment by raphaelthegreat** [comment]
The new header looks great! Some suggestions:
* Status can be updated to mention that smaller 2D games work.
* Instead of the video that isn't the best of quality, try putting some of the screenshots in showcase discord channel for game images, those will probably look better here

**Comment by Xphalnos** [comment]
Ready for review or changes !

**Comment by raphaelthegreat** [comment]
The screenshot doesn't seem to be showing in the demo there (probably because you put the link to the main repo. also it's hidden behind a link, not sure?)
Also might be a nitpick but I think the screenshots are better placed right below the logo like before compared to status section

**Comment by Xphalnos** [comment]
Now the readme looks like this, is it better?

image

**Comment by raphaelthegreat** [comment]
Looks good 👍

**Pull request merged**
