### PR TITLE
Help - improvement

### PR DESCRIPTION
**Pull request by DanielSvoboda**
issue suggestions: https://github.com/shadps4-emu/shadPS4/issues/1362
- [X] Buttons in 'About' and clicking takes you to the respective links.

I removed the  submenu for 'Keys and Shortcuts' and left only the buttons for the external links of the sites.
I think it would be better to implement this in another PR so that it doesn't get stuck.

ezgif-5-c411d750db
ezgif-5-c20a1c4ad1

### CODE REVIEW

**Comment by GHU7924** [comment]
1) I do not know what about YouTube (maybe it is not needed), but I know for sure that there are still links - https://shadps4.net  and https://x.com/shadps4
* Title: I'm not completely sure how "Keyboard shortcuts" or "Hotkeys" would be better.
** "Hotkey" - I drew the third line in the menu list (it was just more convenient for me), 
Sample 1
but in fact it should be the first or second, so it would be correct.

2) ShadPS4 has the ability to change the theme, 
Themes

so I think the color should be adjusted to the selected theme (I mean the link icons) .

3) 
>Maybe reduce the size of that logo on the left a little.

If all the links fit, then perhaps the logo on the left should not be touched.

4) I drew my version of Keyboard shortcuts on top of the "About shadPS4" window, so I don't know how to do it right, because new functions (keys) may still be added.

I think you can make a temporary option.
Make the window look like "About shadPS4" (or copy the old version), that is, you take the old version and just change the text.
I may have been a little hasty and pointed out some buttons that don't exist yet, because they haven't been merged with Main.
Something like this will do:
Interfeice456

**Comment by Linear524** [comment]
Maybe F12 = Screenshot into dedicated screenshot folder inside ShadPS4 folder ?)))

**Comment by DanielSvoboda** [comment]
> Maybe F12 = Screenshot into dedicated screenshot folder inside ShadPS4 folder ?)))

Screen capture has not been implemented yet, but if renderdoc is enabled and you press F12, it captures the information for debugging this system and saves it in the captures folder if I'm not mistaken. I'll continue this PR this weekend...

**Comment by GHU7924** [comment]
https://github.com/shadps4-emu/shadPS4/pull/1356#issuecomment-2478201400 As soon as PR 1356 is merged with Main, we will have new functions.

F7 - Captures mouse and enables mouse movement input
F8 - Reparse keyboard input
F9 - Pause emulator (in Debug Menu)
F10 - FPS counter
LCtrl + F10 - Debug Menu
F11 - Fullscreen
F12 - Сaptures the information for debugging this system and saves it in the captures folder (with RenderDoc debugging enabled)
(I haven't checked and, to be honest, I don't know how to describe it more briefly)

@DanielSvoboda How many links are left in the end? 
GitHub, Discord, Ko-fi.com, YouTube???, X.com??, ShardPS4.net? 
If there are all 6, then you will have to reduce the PS4 icon and center the icons.

About links

If possible, it is worth implementing a screenshot function to make it easier to capture a moment or a graphical error, if one appears.

Move the F12 function to one of the F1-F6 keys, and make F12 a screenshot function (If there is a desire and an opportunity).

**Comment by GHU7924** [comment]
Links with different themes look good.
Themes

I don't know about that, is it necessary here? I'm talking about the controller. 50/50
k

If you leave it, you need to improve it, and the background should be transparent in the image so that it looks uniform with the rest of it. But I think you wanted to do it anyway)) Example of changes:
k2

I think it's working out very well.

**Comment by DanielSvoboda** [comment]
@GHU7924 I made some changes as you mentioned, now it's a little better. I also put the text inside a group.

image

**Comment by kalaposfos13** [comment]
Just a quick note: This is neither my nor the current default keybinds, but I guess this would have to be rewritten anyway when my pull request gets merged

**Comment by GHU7924** [comment]
@DanielSvoboda I think it looks amazing. Great job.

Edit:

With the implementation of the keyboard and mouse from @kalaposfos13 , it will be possible to do something like this:
k3

P.S. It's just a sketch, as I see it roughly, but it needs to be refined and brought to the same style.
P.S.S. L1 = LMB + LShift and R2 = RMB + LShift - in my opinion, it would be better, but as it is by default, so it is.

**Comment by DanielSvoboda** [comment]
As this PR doesn't have much priority, I even left it as a draft because there are some things missing, I'll wait a bit for things to unfold and then I'll make the necessary changes later.

**Comment by GHU7924** [comment]
You're right, the main thing here is not to rush. I just wrote (made a sketch) for an example, but I'm not saying that this is how it should be. I believe you, you will do well.

**Comment by GHU7924** [comment]
Does it make sense to add system requirements?

Ab
( I didn't try very hard, but just quickly made a sketch, so the system requirements are identical )

Edit: (Additional information)
I suggested adding system requirements because I have seen such questions from users several times on some forums.
https://github.com/shadps4-emu/shadPS4/issues/1362#issuecomment-2469208491 Also, the second part of my comment can be implemented here. There will be general links and leads to the issues section. I think this is quite a good addition.

I also thought again about the implementation of the "Keys and shortcuts" window.
Here is a new view of the controller image, although when I did it, I entered my control settings for the keyboard, but I did not correct it anymore.

k4

But I didn't come up with anything about the "Share" button, because I don't know what is planned to be done in the emulator for this button and what functionality it will have, if at all.

I marked the PS button as (M = Menu), but I also don't know for its implementation, but let it be so for now.

**Comment by DanielSvoboda** [comment]
I removed the keys shortcuts and left only the buttons for the external links of the sites.
I think it would be better to implement this in another PR so that it doesn't get stuck

**Comment by GHU7924** [comment]
> I removed the keys shortcuts and left only the buttons for the external links of the sites. I think it would be better to implement this in another PR so that it doesn't get stuck

Yes, this makes sense, especially since we can mark the new PR as a continuation of this, and the ideas and improvements that will be here can be transferred to future PR. Also, a new PR can be started only after combining the keyboard PR.

EDIT: Future PR - Interface update.

**Pull request merged**
