### PR TITLE
Add PM4 opcodes

### PR DESCRIPTION
**Pull request by dbz400**

### CODE REVIEW

**Comment by polybiusproxy** [comment]
Where did you see these used?

**Comment by dbz400** [comment]
From CUSA01633 : Final Fantasy XV

[Debug] <Critical> liverpool.cpp:ProcessCompute:561: Unreachable code!
Unknown PM4 type 3 opcode 0x78 with count 2


I can remove the others (0x34, 0x59, 0x80) since they haven't seen from any games yet .

**Comment by raphaelthegreat** [comment]
I think its okay to have them for futureproofing purposes

**Review by polybiusproxy — APPROVED** [review]

**Comment by polybiusproxy** [comment]
> From CUSA01633 : Final Fantasy XV
> 
> [Debug] liverpool.cpp:ProcessCompute:561: Unreachable code! Unknown PM4 type 3 opcode 0x78 with count 2
> 
> I can remove the others (0x34, 0x59, 0x80) since they haven't seen from any games yet .

Rewind (0x59) used by DRIVECLUB (CUSA00003)

**Comment by gandalfthewhite19890404** [comment]
0x34 used by WWE 2K15 (CUSA00784)

**Pull request merged**
