### PR TITLE
cmake: Allow disabling discord rpc

### PR DESCRIPTION
**Pull request by raphaelthegreat**
Discord RPC is basically abandonware at this point and may not compile everywhere

### CODE REVIEW

**Comment by georgemoralis** [comment]
probably need an #ifdef in the file that calls it as well

**Comment by polybiusproxy** [comment]
What other alternatives do we have?

**Comment by raphaelthegreat** [comment]
> probably need an #ifdef in the file that calls it as well

Done

**Comment by raphaelthegreat** [comment]
> What other alternatives do we have?

I don't think there is an open alternative to this. Discord has some sdk stuff for integration but haven't done any research if they can be used, and nobody seems to use them anyway

**Comment by georgemoralis** [comment]
there is a new interface for discord as i remember

**Pull request merged**
