### PR TITLE
pthread: Change minimum stack for HLE to additional stack.

### PR DESCRIPTION
**Pull request by squidbus**
May fix some remaining stack space issues with HLE.

@Emulator-Team-2 Can you check with Gintama Rumble and cubeb audio with this?

### CODE REVIEW

**Comment by raphaelthegreat** [comment]
Should we also consider moving audio processing into a separate host thread to alleviate stack issues from cubeb?

**Comment by squidbus** [comment]
> Should we also consider moving audio processing into a separate host thread to alleviate stack issues from cubeb?

The actual processing done by cubeb is already in another thread but I suppose we could move the initialization to a thread as well, yes. The only part at issue here is the `cubeb_stream_init` call from `sceAudioOpen`, and only on Windows release builds for some reason. Although there's no guarantee we won't face this issue with other HLE so would like to have a more robust solution in place (at least until we can do something better like a separate HLE stack).

**Comment by raphaelthegreat** [comment]
If its only the initialization code that is an issue, you can wrap it with std::async I think for easier effect
```cpp
std::async([&] {
// init
}).get();
```

**Comment by squidbus** [comment]
> If its only the initialization code that is an issue, you can wrap it with std::async I think for easier effect

Yes that looks fairly simple but are we going to litter this pattern all around the codebase whenever this happens again?

**Comment by raphaelthegreat** [comment]
No that would look kinda ugly. If this happens again we should look into HLE stacks I think

**Comment by raphaelthegreat** [comment]
Note I agree with this PR as a change, this isnt against it

**Comment by squidbus** [comment]
> Note I agree with this PR as a change, this isnt against it

Okay thanks, I think if this doesn't work (it could be a passed stack pointer as well) I will go with `std::async` or similar as you suggested.

**Comment by Emulator-Team-2** [comment]
Fixes issue in `Gintama Rumble` with selected (cubeb) audio backend.

##

`Disgaea 4 Complete+` still hangs, when the opening video starts playing with selected (cubeb) audio backend. This doesn't happen with (sdl).

Log:
[shad_log.zip](https://github.com/user-attachments/files/18267854/shad_log.zip)

**Comment by squidbus** [comment]
> `Disgaea 4 Complete+` still hangs, when the opening video starts playing with selected (cubeb) audio backend. This doesn't happen with (sdl).

This is a different and I'll have to look into it for another PR.

**Pull request merged**
