### PR TITLE
compatibility_data: various fixes

### PR DESCRIPTION
**Pull request by f8ith**
Addresses #1843 

* Disable compatibility data by default while issues are ironed out
* Adds timeout when fetching issue data 
* Adds configuration option to enable compatibility_data: `compatibilityEnabled`, `checkCompatibilityOnStartup`

### CODE REVIEW

**Comment by GHU7924** [comment]
>compatibilityEnabled
Do not show status column if it is not enabled

@f8ith That's a great idea.

**Comment by Hermiten** [comment]
Can we add it on the GUI ?
Maybe on the View TAB or simply on the Settings->Configure one

Thanks anyway for the fix :)

**Comment by GHU7924** [comment]
@Hermiten I suggested doing it this way https://github.com/shadps4-emu/shadPS4/pull/1668#issuecomment-2555835469 (In more detail)
But now we need to add something like a checkbox: Compatibility status.

EDIT: I've updated a little what I suggested earlier.


I think it would be more correct to do this if updates depend on whether the "Enable Compatibility Data" checkbox is checked or not. For example, if it is not enabled, you will not be able to check the box "Check for Updates at Startup" or click check for updates.

**Comment by f8ith** [comment]
@Hermiten #1855

**Pull request merged**
