### PR TITLE
use ComPtr in gui_context_menus.h

### PR DESCRIPTION
**Pull request by oltolm**
see title

### CODE REVIEW

**Comment by georgemoralis** [comment]
ok and why that is a better solution?

**Comment by oltolm** [comment]
> ok and why that is a better solution?

Because the [`ComPtr`](https://learn.microsoft.com/en-us/cpp/cppcx/wrl/comptr-class?view=msvc-170) is a smart pointer that automatically does reference counting. It is best practice for writing COM code on Windows. That is what Microsoft recommends.

**Comment by oltolm** [comment]
ping

**Comment by georgemoralis** [comment]
@oltolm since there are a lot of changes do a rebase first just in case :)

**Comment by raphaelthegreat** [comment]
You seem to have removed some pragma GCC wrappers around vma include. Can you restore/remove any unrelated changes so this can be merged

**Comment by oltolm** [comment]
> You seem to have removed some pragma GCC wrappers around vma include. Can you restore/remove any unrelated changes so this can be merged

I removed the pragmas because of this discussion https://github.com/shadps4-emu/shadPS4/pull/749. They were unnecessary.

**Review by raphaelthegreat — APPROVED** [review]
Ah I see

**Pull request merged**
