### PR TITLE
Fix file path (3rd time)

### PR DESCRIPTION
**Pull request by ngoquang2708**
Third time's the charm.

### CODE REVIEW

**Comment by Deathedit** [comment]
red dead is loading on my local build :)

**Comment by ngoquang2708** [comment]
> red dead is loading on my local build :)

With this PR?

**Comment by Deathedit** [comment]
> > red dead is loading on my local build :)
> 
> With this PR?

no, replace code myself

**Comment by ngoquang2708** [comment]
What did you replace?

**Comment by Deathedit** [comment]
> What did you replace?

`while (size_t pos = corrected_path.find("//") != std::string::npos) {` to     `
size_t pos = corrected_path.find("//");
    while (pos != std::string::npos) {
`

**Comment by ngoquang2708** [comment]
Yeah that what I did in this PR.

**Comment by Deathedit** [comment]
> Yeah that what I did in this PR.

i think misunderstood you at first

**Comment by ngoquang2708** [comment]
@Deathedit Please re-test this PR when the action is done building for me. Thanks.

**Comment by Deathedit** [comment]
> @Deathedit Please re-test this PR when the action is done building for me. Thanks.

i just tested it, it seems to load my games without any problem

**Comment by ngoquang2708** [comment]
> i just tested it, it seems to load my games without any problem

Thanks.

**Pull request merged**
