### PR TITLE
Don't read uninitialized memory in `sceSystemServiceReceiveEvent`

### PR DESCRIPTION
**Pull request by korenkonder**

### CODE REVIEW

**Comment by polybiusproxy** [comment]
I believe it'll be better to just move the log after the nullptr check.

**Comment by georgemoralis** [comment]
> I believe it'll be better to just move the log after the nullptr check.

agree

**Comment by viniciuslrangel** [comment]
The `event` in this function is an out parameter, so we shouldn't read at all from that

**Comment by polybiusproxy** [comment]
Oh, in that case...

**Pull request merged**
