### PR TITLE
Update ru translation for 0.5.0

### PR DESCRIPTION
**Pull request by f1amy**
* Added translations for new strings added in 0.5.0
* Fixed some old translations

### CODE REVIEW

**Comment by f1amy** [comment]
Had a little bit of trouble with conflicts due to main branch being force pushed by @raphaelthegreat

**Comment by GHU7924** [comment]
RusLocalization

**Comment by f1amy** [comment]
@GHU7924 I don't know a way to translate "s" in UI, it seems to be hardcoded for all languages

**Comment by mailwl** [comment]
@flamy, open a new issue about hardcoded string value "s" in setup window

**Comment by GHU7924** [comment]
@f1amy So I wrote - if it's possible, but "No" means "no", fine.

One more thing, "Never Played" - "Нет", maybe "Вы не играли", will it fit?

**Comment by mailwl** [comment]
"Never Played" - "Никогда"?

**Comment by f1amy** [comment]
@GHU7924 New text should fit, will check when it compiles

Original thought was "Времени в игре" -> "Нет", so it is concise
"Времени в игре" -> "Вы не играли" is fine to me

**Comment by f1amy** [comment]
> "Never Played" - "Никогда"?

"Времени в игре" -> "Никогда"
Does not sound good

**Comment by f1amy** [comment]
image

Looks good 👍

**Comment by mailwl** [comment]
"Вы не играли" looks lower than other labels (but higher, than "Bloodborne"). Something wrong with alignments, but not translation, of course

**Comment by f1amy** [comment]
> "Вы не играли" looks lower than other labels (but higher, than "Bloodborne"). Something wrong with alignments, but not translation, of course

Yeah, that does appear to be the case

Serial number, Firmware, Size, Version text is one pixel higher than Name and Play Time

398784460-b1e9b089-2d51-44af-89fd-d839006618d5

**Comment by f1amy** [comment]
> Serial number, Firmware, Size, Version text is one pixel higher than Name and Play Time

Don't know how can I fix this as it's not directly a localization issue

Some other problem is on this PR #1922 is amplified somewhat due to some text being longer, and it would be great if we could fix it, but again, the issue should not block this PR

Other than that, PR should be considered good to go

**Comment by GHU7924** [comment]
@DanielSvoboda can you see if it is possible and where it is worth making edits?

EDIT: The "Size" & "Play Time" columns are also unavailable for translation. MB, GB and h, m, s.

**Comment by DanielSvoboda** [comment]
> @DanielSvoboda can you see if it is possible and where it is worth making edits?
> 
> EDIT: The "Size" & "Play Time" columns are also unavailable for translation. MB, GB and h, m, s.

image

Are these letters correct for Russian?

B  Б
KB КБ
MB МБ
GB ГБ
TB ТБ

    
h ч
m м
s с

**Comment by GHU7924** [comment]
>Are these letters correct for Russian?

Yes

We discussed this point here even earlier.


This is also not available for translation. But here you can translate "s" to "сек". If possible.

**Comment by DanielSvoboda** [comment]
Should I put 'сек' in both the 'timeout' and the 'PlayTime' menu, or 'сек' only in the 'timeout'?

**Comment by GHU7924** [comment]
"Timeout" will be enough.

**Comment by DanielSvoboda** [comment]
What is the best Russian translation for: "Audio Backend"
because the sdl and cubeb option was added to the menu
So I'll take advantage and include this too

**Comment by mailwl** [comment]
chatgpt says:

> "Audio Backend" можно перевести на русский язык как "**аудиоподсистема**" или "**Звуковая подсистема**".

second variant looks good

**Comment by GHU7924** [comment]
The word "Backend" is quite difficult to apply to the Russian language. 
But if you look at the information about SDL and Cubeb, then I agree with @mailwl that the second option is suitable.

@DanielSvoboda Thank you for your help.

**Comment by GHU7924** [comment]
@f1amy Вы можете создать новый PR "Update Russian translation" ?

Нам необходимо сверить переводы. Как я понял самый полный перевод - en.ts (1417 строк),
в русской локализации ru_Ru.ts (1408 строк), скорее всего могут быть как отсутствующие элементы, так и наоборот лишние.
Я не знаю возможно ли два этих файла (en.ts и ru_Ru.ts) сравнить построчно, но если есть такая возможность, то было бы здорово.
С самым последним билдом (v 0.6.1 f3810ce) на момент написания этого комментария, я нашёл такие различия:
Localization
debugloc

Я не знаю, всё ли доступно для локализации из перечисленного, но если я ничего не упустил, то здесь все несостыковки.

Update: Произошло слияние с PR 1356, поэтому теперь также необходима локализация контроллера и его справки.
controller

**Comment by yeager** [comment]
Try "lupdate ru_RU.ts en.ts -ts new_ru.ts"

**Comment by f1amy** [comment]
@GHU7924 Да, постараюсь завтра

**Pull request merged**
