### PR TITLE
Readme: improvements

### PR DESCRIPTION
**Pull request by Xphalnos**
I improved the readme so that it is more understandable.  I also removed the Build Status because it's not useful to put it in the main readme. I updated GPUCode's nickname to raphaelthegreat.

### CODE REVIEW

**Comment by georgemoralis** [comment]
doesn't look bad , but why erasing build status ?

**Comment by Xphalnos** [comment]
> doesn't look bad , but why erasing build status ?

I removed the build status because I don't see the point of putting it in the main readme.  If you want me to put it back I can do that.

**Comment by georgemoralis** [comment]
we want it back pls

**Comment by Xphalnos** [comment]
It's okay, I put the build status back.

**Comment by georgemoralis** [comment]
psucien https://github.com/psucien , should be add to the team (after raph)

**Comment by Xphalnos** [comment]
psucien added !

**Pull request merged**
