### PR TITLE
Add auto stubs, update aerolib, faster init

### PR DESCRIPTION
**Pull request by skmp**
### Overview
- Adds a python script to generate the tables from function list
- Auto resolves the stubs

### Details
- Reworked to use the small aerolib, as the full version is too big to include in such a way
- Uses a sorted array instead of std::map

@georgemoralis thoughts?

### CODE REVIEW

**Comment by skmp** [comment]
Hmm, looks like clang needs ~ 2GB to compile the file, which we don't have in the runner.

**Comment by georgemoralis** [comment]
i think we should reduce the NID to standard libs only

**Comment by skmp** [comment]
yeah, will re-work with the original list

**Comment by skmp** [comment]
Re worked with the original list ~

**Comment by georgemoralis** [comment]
ci got stucked :D

**Comment by skmp** [comment]
This clearly needs a different approach, CI can't handle such big source files

**Comment by skmp** [comment]
This now uses a slot-based system, and will resolve up to 128 stubs to named stubs. Hopefully solves compile time issues?

**Comment by skmp** [comment]
Compile time seems to be inline with other test runs now. @georgemoralis are there any multi threading concerns around the linker code right now? The stubs code needs a mutex to be multi threading safe.

**Comment by georgemoralis** [comment]
linker class has a mutex  (linker.h) you can do a Lib::LockMutexGuard lock(m_mutex); to make sure

**Pull request merged**
