### PR TITLE
Add other 64-bit floating point shader instructions

### PR DESCRIPTION
**Pull request by dbz400**
For CUSA00897 https://github.com/shadps4-emu/shadPS4/issues/496

[Render.Recompiler] translate.cpp:LogMissingOpcode:452: Unknown opcode V_MUL_F64 (891, category = VectorALU)
[Render.Recompiler] translate.cpp:LogMissingOpcode:452: Unknown opcode V_FMA_F64 (866, category = VectorALU)
[Render.Recompiler] translate.cpp:LogMissingOpcode:452: Unknown opcode V_RCP_F64 (510, category = VectorALU)

### CODE REVIEW

**Comment by polybiusproxy** [comment]
You seem to only have added the function definitions

**Comment by polybiusproxy** [comment]
Were `V_ADD_F64`/`V_MIN_F64` tested? Did you encounter them on any game?

**Comment by dbz400** [comment]
@polybiusproxy Didn't see that two yet but i hope the implementation correct that can help other games 🙏

**Comment by polybiusproxy** [comment]
It might be best to get rid of them and only make an implementation if we see a game hitting those.

**Comment by dbz400** [comment]
@polybiusproxy Per your advice , removed V_ADD_F64 and V_MIN_F64

**Review by polybiusproxy — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
