### PR TITLE
Improved Dark theme, search bar and icon theme

### PR DESCRIPTION
**Pull request by Xphalnos**
- I improved the Dark theme by changing the colors a bit.
- I improved the search bar by increasing the border and putting the background in black for more contrast
- I added a black outline for the search bar for the white theme
- I added a better icon for the theme
- I updated the French translations

Dark:
Capture d'écran 2024-09-07 113211 Capture d'écran 2024-09-07 112458

Light:
Capture d'écran 2024-09-07 113223 Capture d'écran 2024-09-07 112517

Green:
Capture d'écran 2024-09-07 113228 Capture d'écran 2024-09-07 112523

Blue:
Capture d'écran 2024-09-07 113232 Capture d'écran 2024-09-07 112528

Purple:
Capture d'écran 2024-09-07 113236 Capture d'écran 2024-09-07 112533

Theme icon:
Capture d'écran 2024-09-07 113218 Capture d'écran 2024-09-07 112507

### CODE REVIEW

**Comment by dima-xd** [comment]
The best way to improve themes is get rid of QPalette and use QDarkStyleSheet instead, just like Citra/Yuzu

**Comment by Xphalnos** [comment]
> The best way to improve themes is get rid of QPalette and use QDarkStyleSheet instead, just like Citra/Yuzu

Sure, but it seems complicated to me. If you want to do it, it could be cool!

**Comment by abouvier** [comment]
Can you also provide a system/default theme that doesn't change anything and make the window looks like other Qt windows?

**Comment by Xphalnos** [comment]
> Can you also provide a system/default theme that doesn't change anything and make the window looks like other Qt windows?

You mean it looks at the OS theme and applies it? (Light/Dark)

**Comment by abouvier** [comment]
> You mean it looks at the OS theme and applies it? (Light/Dark)

Why is it needed at all? If all the theme related stuff is removed, the window will get its appearance from the system theme configured globally right?

**Comment by Xphalnos** [comment]
> > You mean it looks at the OS theme and applies it? (Light/Dark)
> 
> Why is it needed at all? If all the theme related stuff is removed, the window will get its appearance from the system theme configured globally right?

I tried but when the light theme is selected on Windows, the icons remain white. I think it is better to do it in another commit

image

**Comment by Xphalnos** [comment]
Ready for merge!

**Pull request merged**
