### PR TITLE
Fix general typos

### PR DESCRIPTION
**Pull request by LeDragoX**
After seeing it was not that complicated, the scope of this PR will be at fixing all the typos found inside the `src` folder.

Like fixing this typo presented here (visi**libi**ty -> visi**bili**ty)
https://github.com/shadps4-emu/shadPS4/blob/243fd0be78d2a7abd1b2b8165c2be2da36d93652/src/core/linker.cpp#L187-L189

### CODE REVIEW

**Comment by Xphalnos** [comment]
For the file that was renamed, you will need to change the name in CMakeLists.txt at [**this line**](https://github.com/shadps4-emu/shadPS4/blob/243fd0be78d2a7abd1b2b8165c2be2da36d93652/CMakeLists.txt#L437).

**Comment by LeDragoX** [comment]
> For the file that was renamed, you will need to change the name in CMakeLists.txt at [**this line**](https://github.com/shadps4-emu/shadPS4/blob/243fd0be78d2a7abd1b2b8165c2be2da36d93652/CMakeLists.txt#L437).

Done, thanks!

**Comment by LeDragoX** [comment]
Fixed the conflicts

**Review by Xphalnos — APPROVED** [review]
This looks good to me. I haven't checked if it compiles correctly but congratulations for the work you've done!

**Comment by LeDragoX** [comment]
> This looks good to me. I haven't checked if it compiles correctly but congratulations for the work you've done!

@Xphalnos It compiles now, thanks! I've learned some `git` tricks after this PR.

**Review by raphaelthegreat — APPROVED** [review]

**Pull request merged**
