### PR TITLE
Implement V_BFM_B32 and V_FFBH_U32

### PR DESCRIPTION
**Pull request by baggins183**
Used by CUSA01127

### CODE REVIEW

**Comment by baggins183** [comment]
I used a bitfieldextract to simplify but just realized the spirv spec has undefined behavior when offset + width of the mask is > 32 so Im gonna change this to the exact formula from the ISA doc:
D.u = ((1<<S0.u[4:0])-1) << S1.u[4:0]

**Comment by baggins183** [comment]
fixed it

**Comment by baggins183** [comment]
threw in V_FFBH_U32.
The sea islands ISA says
D.u = position of first 1 in S0 from MSB; D=0xFFFFFFFF if S0==0

so sounds like it counts from the leftmost bit (MSB) instead of SPIR-V which is from the rightmost (LSB)

**Comment by ShaggyLorean** [comment]
crash persists after the implement still

**Comment by ShaggyLorean** [comment]
baggins183 is there somewhere I can contact w u?

**Comment by LeDragoX** [comment]
The new error is:
```ts
[Debug] <Critical> liverpool.cpp:ProcessCompute:518: Unreachable code!
Invalid PM4 type 0
```
Logs: [shad_log.txt](https://github.com/user-attachments/files/16821734/shad_log.txt) and [sys_modules_vk_validation_shad_log.txt](https://github.com/user-attachments/files/16821766/sys_modules_vk_validation_shad_log.txt)
PM4 and Shaders Dump: [PM4 + Shaders.zip](https://github.com/user-attachments/files/16821782/PM4.%2B.Shaders.zip)

**Comment by ShaggyLorean** [comment]
CUSA01127's new error is `Unhandled exception: Incompatible types F32 and U32`

**Comment by efigr** [comment]
Skipping the PM4 error, I get a `Incompatible types F32 and U32` error after compute shader `0x229c75fadec08ca5`

```
[Render.Vulkan] <Info> vk_shader_cache.cpp:CompileModule:119: Compiling cs shader 0x229c75fadec08ca5 
[Debug] <Critical> liverpool.h:unhandled_exception:1100: Unreachable code!
Unhandled exception: Incompatible types F32 and U32
```
[Log + PM4 & Shader Dump.zip](https://github.com/user-attachments/files/16821934/Log.%2B.PM4.Shader.Dump.zip)

**Comment by ElBread3** [comment]
Tested this PR but this game for me just spams this cryptic stub "select" on a black screen, which I've still been experiencing on main, just the word "select" is weird as it's not even associated with a sce. Edit: Saw this in other's logs too but still good to question a bit, as what does this function even do, select what?

[Core] <Error> stubs.cpp:CommonStub:42: Stub: select (nid: T8fER+tIGgk) called, returning zero to 0x900a76259
[Core] <Error> stubs.cpp:CommonStub:42: Stub: select (nid: T8fER+tIGgk) called, returning zero to 0x900a76259
[Core] <Error> stubs.cpp:CommonStub:42: Stub: select (nid: T8fER+tIGgk) called, returning zero to 0x900a76259

[ptlog.txt](https://github.com/user-attachments/files/16821991/ptlog.txt)

**Comment by baggins183** [comment]
> The new error is:
> 
> ```ts
> [Debug] <Critical> liverpool.cpp:ProcessCompute:518: Unreachable code!
> Invalid PM4 type 0
> ```
> 
> Logs: [shad_log.txt](https://github.com/user-attachments/files/16821734/shad_log.txt) and [sys_modules_vk_validation_shad_log.txt](https://github.com/user-attachments/files/16821766/sys_modules_vk_validation_shad_log.txt) PM4 and Shaders Dump: [PM4 + Shaders.zip](https://github.com/user-attachments/files/16821782/PM4.%2B.Shaders.zip)



This PR isnt gonna make PT run magically lol. I was just doing some opcodes I saw were unimplemented in the compiler
That's a GNM/graphics driver thing

**Comment by baggins183** [comment]
Ill look at the PM4 thing later though because I do want to get involved with that. Looks like type 0 packets arent supported. The SI programming guide makes it sound like they are rare/not recommended, and looking at the emu, usually type 3 packets are handled

**Comment by baggins183** [comment]
> CUSA01127's new error is `Unhandled exception: Incompatible types F32 and U32`

Ill look at this. Not sure if its related to my code. Im new to shadps4

**Comment by baggins183** [comment]
btw is there a way to autofix the clang format stuff from github?

**Comment by LeDragoX** [comment]
> This PR isnt gonna make PT run magically lol. I was just doing some opcodes I saw were unimplemented in the compiler
>  That's a GNM/graphics driver thing

I know, it's out of the scope of this PR, I just tested it and thrown the logs here, cause it may help you somehow. I know where to put my expectations, of course there's a lot of work to do before making the game work, I respect what you have done, it's not easy.

> btw is there a way to autofix the clang format stuff from github?

iirc it doesn't, you will need to fix it manually, usually you'll need to override the lines containing `-` with the new ones containing `+`.

**Comment by baggins183** [comment]
> Skipping the PM4 error, I get a Incompatible types F32 and U32 error after compute shader 0x229c75fadec08ca5

Weird, I cant repro this. Lemme try rebasing. Guessing its not related to this PR

[shad_log.txt](https://github.com/user-attachments/files/16822443/shad_log.txt)

**Comment by baggins183** [comment]
Using these filters btw
logType = "sync"
logFilter = "*:Critical Render.Recompiler:Info Render.Vulkan:Info"

**Comment by efigr** [comment]
> > Skipping the PM4 error, I get a Incompatible types F32 and U32 error after compute shader 0x229c75fadec08ca5
> 
> Weird, I cant repro this. Lemme try rebasing. Guessing its not related to this PR
> 
> [shad_log.txt](https://github.com/user-attachments/files/16822443/shad_log.txt)

Oh yeah, should've clarified it was done on the latest main at the time - I locally compiled and built the changes,

**Comment by efigr** [comment]
I'll give it another proper test on my end to confirm if I keep getting it.

**Comment by efigr** [comment]
Yep, latest main + this PR, and skipping the PM4 error:

```
[Render.Vulkan] <Info> vk_shader_cache.cpp:CompileModule:119: Compiling cs shader 0x229c75fadec08ca5 
[Debug] <Critical> liverpool.h:unhandled_exception:1100: Unreachable code!
Unhandled exception: Incompatible types F32 and U32
```
[shad_log.txt](https://github.com/user-attachments/files/16822485/shad_log.txt)

EDIT: Yeah, I should add that your PR does probably work as intended, and any further issues are a P.T. specific thing. Probably best to ignore this lol.

**Comment by baggins183** [comment]
Weird. Still cant repro after rebasing
I dont see 229c75fadec08ca5 in my shader dumps folder either or getting compiled in my log.
My log stops on the pm4 type 0 error also. Idk if you are getting further ahead than me 

I will compare the logs more

**Comment by baggins183** [comment]
I am using a debug build so I crash from the pm4 type 0 assert. Maybe related

**Comment by efigr** [comment]
> Weird. Still cant repro after rebasing I dont see 229c75fadec08ca5 in my shader dumps folder either or getting compiled in my log. My log stops on the pm4 type 0 error also. Idk if you are getting further ahead than me
> 
> I will compare the logs more

Yeah so by default it will stop on the PM4 type 0 error, but you can skip past it by commenting out the assert and adding a `break;` instead. Obviously a hacky way of brute forcing progression, but I don't think it's of any concern to this particular PR.

**Comment by baggins183** [comment]
Cool. I will look at the pm4 stuff tonight. I am more familiar with the compiler stuff and not so much the GNM driver stuff, but do want to learn

**Comment by efigr** [comment]
> Cool. I will look at the pm4 stuff tonight. I am more familiar with the compiler stuff and not so much the GNM driver stuff, but do want to learn

Understandable, best of luck!

**Comment by ShaggyLorean** [comment]
Thanks to both of you! Good luck to everyone working on P.T.

**Comment by baggins183** [comment]
FYI I dont think those are real type 0 packets.
Its just a bunch of zeroed memory. That will technically look like a bunch of type 0 packets that each write 0 to the 0th register in the register file. Which makes no sense, so I think theres some other bug going on

**Comment by lzardy** [comment]
> Tested this PR but this game for me just spams this cryptic stub "select" on a black screen, which I've still been experiencing on main, just the word "select" is weird as it's not even associated with a sce. Edit: Saw this in other's logs too but still good to question a bit, as what does this function even do, select what?
> 
> [Core] stubs.cpp:CommonStub:42: Stub: select (nid: T8fER+tIGgk) called, returning zero to 0x900a76259 [Core] stubs.cpp:CommonStub:42: Stub: select (nid: T8fER+tIGgk) called, returning zero to 0x900a76259 [Core] stubs.cpp:CommonStub:42: Stub: select (nid: T8fER+tIGgk) called, returning zero to 0x900a76259
> 
> [ptlog.txt](https://github.com/user-attachments/files/16821991/ptlog.txt)

For record, this `select` is for `vectormath`, including matrix and gpu transforms. It is part of commons includes (among other similar namespaces).

**Comment by lzardy** [comment]
> [Core] stubs.cpp:CommonStub:42: Stub: select (nid: T8fER+tIGgk) called, returning zero to 0x900a76259
> [ptlog.txt](https://github.com/user-attachments/files/16821991/ptlog.txt)

For record, this `select` is for `vectormath`, including matrix and gpu transforms. It is part of commons includes (among other similar namespaces).

**Comment by baggins183** [comment]
> > [Core] stubs.cpp:CommonStub:42: Stub: select (nid: T8fER+tIGgk) called, returning zero to 0x900a76259
> > [ptlog.txt](https://github.com/user-attachments/files/16821991/ptlog.txt)
> 
> For record, this `select` is for `vectormath`, including matrix and gpu transforms. It is part of commons includes (among other similar namespaces).

No, Im pretty sure its for this: https://man7.org/linux/man-pages/man2/select.2.html
and in context of PT its probably related to networking. It gets called in a loop by "NioSelectorThread"

**Comment by baggins183** [comment]
Related to issue #496

**Review by raphaelthegreat — APPROVED** [review]

**Pull request merged**
