### PR TITLE
video_core/renderer_vulkan: Ignore unsupported shader stages

### PR DESCRIPTION
**Pull request by polybiusproxy**
Avoids PSPHD games from compiling geometry shaders.

### CODE REVIEW

**Comment by georgemoralis** [comment]
but that is a hack right , at least we probably can make an option for this

**Comment by polybiusproxy** [comment]
> but that is a hack right , at least we probably can make an option for this

It's not a hack, unsupported stages are not supposed to be translated.

**Comment by georgemoralis** [comment]
ignoring them will not fix the issue ;P

**Review by raphaelthegreat — APPROVED** [review]

**Comment by polybiusproxy** [comment]
> ignoring them will not fix the issue ;P

Better that than making it compile them :p 
However I missed something on this PR and that is logging that there's an unsupported stage on the pipeline, like it did before.

**Pull request merged**
