### PR TITLE
Network libs fixes , stubs and more

### PR DESCRIPTION
**Pull request by georgemoralis**

### CODE REVIEW

**Comment by georgemoralis** [comment]
@squidbus can you help a bit with macOS failures?

**Comment by squidbus** [comment]
> can you help a bit with macOS failures?

`gethostname` is in `unistd.h`. This should be the case on Linux as well, I assume its being included transitively currently.

**Comment by squidbus** [comment]
It looks like you will need both `unistd.h` and `netdb.h` to have both `gethostname` and `gethostbyname`.

**Comment by georgemoralis** [comment]
> It looks like you will need both `unistd.h` and `netdb.h` to have both `gethostname` and `gethostbyname`.

doesnt' seem to work ;/

**Comment by squidbus** [comment]
> doesnt' seem to work ;/

You removed `netdb.h` in your last commit

**Comment by georgemoralis** [comment]
> > doesnt' seem to work ;/
> 
> You removed `netdb.h` in your last commit

thanks!

**Comment by raphaelthegreat** [comment]
I don't see the point of the share play and remote play stubs. Unless you want to suppress their logging which isn't done here, we probably wont be implementing them soon

**Comment by georgemoralis** [comment]
> I don't see the point of the share play and remote play stubs. Unless you want to suppress their logging which isn't done here, we probably wont be implementing them soon

all the functions i implemented are returning not available features , so it will probably prevent a game from asking them (at least that is what it does in re6)

**Pull request merged**
