### PR TITLE
Ajm

### PR DESCRIPTION
**Pull request by georgemoralis**
WIP :D

### CODE REVIEW

**Comment by Foul-Tarnished** [comment]
BLOODBORNE ?!

**Comment by rafael-57** [comment]
4462cfa - CUSA03173

Tested Bloodborne a lot during various versions of this branch, It seems in a really good state right now. 
Doesn't crash/hang the emulator anymore, performs well, sound play fine the first time. I have a 5800X3D.

OST, dialogue, sound effects from menus/weapons/hunter tools/enemies all play.

Tested for around 50 mins today and the sound didn't break yet. Bugs that caused 2nd phase boss music to not play or bug after 1 min 30 secs are gone too. Beaten father Gascoigne and the audio was very consistent.

Would upload log but it's 60mb :D Right before merging I would remove most logging and the linux hack for BB in thread_management.cpp.

**Comment by smiRaphi** [comment]
Persona 3 Dancing doesn't crash anymore now and again runs until the first loading screen but with sound :D

**Comment by GHU7924** [comment]
Build f9243bd - CUSA03173

I apologize for writing late, I just tested this build.
I set aside some time for the test, so I connected cheats to speed up the process.
I quickly ran through the problem areas that I indicated in #1460.
Everything seems to be fixed. I stopped at the same place, I didn't go any further, BUT
I had a "Critical" moment as soon as I defeated Father Gascoigne, but maybe it's connected to something else.

>[Lib.Ajm] <Info> ajm.cpp:sceAjmBatchWait:593: called context = 1, batch_id = 1, timeout = 0
>[Lib.Ajm] <Info> ajm.cpp:sceAjmBatchStartBuffer:416: called context = 1, batch_size = 0xa0, priority = 40
>[Render.Vulkan] <Warning> liverpool.cpp:ProcessGraphics:553: GDS memory read
>[Render.Vulkan] <Warning> liverpool.cpp:ProcessGraphics:553: GDS memory read
>[Render.Vulkan] <Warning> liverpool.cpp:ProcessGraphics:553: GDS memory read
>[Render.Vulkan] <Warning> liverpool.cpp:ProcessGraphics:553: GDS memory read
>[Render.Vulkan] <Warning> liverpool.cpp:ProcessGraphics:553: GDS memory read
>[ImGui] <Error> imgui_core.cpp:CheckVkResult:23: Vulkan error ErrorDeviceLost
>[Debug] Critical vk_scheduler.cpp:operator():147: Assertion Failed!
>Device lost during submit

I'll try to run more tests later, but slowly.

**Comment by AwesomeSoftware79** [comment]
Build https://github.com/shadps4-emu/shadPS4/commit/f9243bdf8d048b376738ad6322c976a8e9e67d0a - CUSA03173

Got these crashes after playing about 20-30 mins.
VRAM usage slowly increased until the crashes happened, up 10 GB VRAM. I am not sure if has something to do.

Crash Nr. 1:
```
[Debug] <Critical> texture_cache.cpp:ResolveDepthOverlap:102: Unreachable code!
```
Crash Nr. 2:
```
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Debug] <Critical> liverpool_to_vk.cpp:operator():650: Assertion Failed!
Unknown data_format=56 and num_format=15
```

**Comment by rafael-57** [comment]
> Build [f9243bd](https://github.com/shadps4-emu/shadPS4/commit/f9243bdf8d048b376738ad6322c976a8e9e67d0a) - CUSA03173
> 
> Got these crashes after playing about 20-30 mins. VRAM usage slowly increased until the crashes happened, up 10 GB VRAM. I am not sure if has something to do.
> 
> Crash Nr. 1:
> 
> ```
> [Debug] <Critical> texture_cache.cpp:ResolveDepthOverlap:102: Unreachable code!
> ```
> 
> Crash Nr. 2:
> 
> ```
> [Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
> [Debug] <Critical> liverpool_to_vk.cpp:operator():650: Assertion Failed!
> Unknown data_format=56 and num_format=15
> ```

Those are related to the GPU (texture cache and liverpool) so not related to this PR thankfully.

**Comment by rainmakerv3** [comment]
Also testing Build https://github.com/shadps4-emu/shadPS4/commit/f9243bdf8d048b376738ad6322c976a8e9e67d0a on Bloodborne (CUSA03173, no mods or patches) I get  

[Debug] <Critical> liverpool.cpp:ProcessGraphics:200: Unreachable code!
Unsupported PM4 type 0 

after some time (maybe 15 minutes). I know that liverpool error is not supposed to be related, but I do wonder if it's a coincidence we seem to be getting all sorts of seemingly new crashes that don't appear to happen on main or on previous ajm builds

**Comment by AwesomeSoftware79** [comment]
Using the same build f9243bd (CUSA03173, no mods) I was able to **complete** the game from start to finish.
Apart from unrelated errors (see my previous comment in this PR), typical vertex explosions, etc. I could not see any AJM-related problems.

GPU VRAM usage is very high, which might be problematic for most people (i.e. after a long period of time without crashing, I got a peak of 18 GB VRAM used).

**Comment by AwesomeSoftware79** [comment]
Sounds stop working when Bloodborne has not been properly closed (i.e. after emulator crash, or not properly exiting the game).

When this happens, we are greeted next time with this message:
image

And we can see a couple of red colored errors in the shadps4 command line:

```
[Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=C:/InstalledGames/CUSA03173\dvdroot_ps4/menu/logo.tpf.dcx, error_message=no such file or directory
[Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=C:/InstalledGames/CUSA03173\dvdroot_ps4/parts/wp_a_6010.partsbnd.dcx, error_message=no such file or directory
[Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=C:/InstalledGames/CUSA03173\dvdroot_ps4/parts/lg_a_9700.partsbnd.dcx, error_message=no such file or directory
[Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=C:/InstalledGames/CUSA03173\dvdroot_ps4/parts/lg_a_9700_l.partsbnd.dcx, error_message=no such file or directory
[Kernel.Pthread] <Error> file_system.cpp:posix_stat:403: posix_stat: error = -2147352574
[Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=C:/InstalledGames/CUSA03173\dvdroot_ps4/menu/.gfx, error_message=no such file or directory
```

At this point, most sounds are missing from the game.

If we then proceed to properly save the game (that means exiting to Bloodborne's main menu, closing the emulator and starting it again so we are not greeted with the error message), the game will eventually have sounds again.

**Comment by GHU7924** [comment]
Still the same Build f9243bd

CUSA02366 (01.00) Beach Buggy Racing.

The first thing I am always greeted with is such a message, but as I understand it, this is due to the fact that it is impossible to connect PSN.



Gameplay

https://github.com/user-attachments/assets/9fed2575-52ed-4a10-b45c-82d08c6a87bb

Now the game has sound.

EDIT: I have removed information not related to this PR. I apologize.

**Comment by Furegato** [comment]
> Also testing Build [f9243bd](https://github.com/shadps4-emu/shadPS4/commit/f9243bdf8d048b376738ad6322c976a8e9e67d0a) on Bloodborne (CUSA03173, no mods or patches) I get
> 
> [Debug] liverpool.cpp:ProcessGraphics:200: Unreachable code! Unsupported PM4 type 0
> 
> after some time (maybe 15 minutes). I know that liverpool error is not supposed to be related, but I do wonder if it's a coincidence we seem to be getting all sorts of seemingly new crashes that don't appear to happen on main or on previous ajm builds

I'm 100% positive that this issue is not related to the AJM PR.
I've been having it for the past month or so and know exactly how to trigger it, with or without the AJM PR.

**Comment by Furegato** [comment]
> Sounds stop working when Bloodborne has not been properly closed (i.e. after emulator crash, or not properly exiting the game).
> 
> When this happens, we are greeted next time with this message: image
> 
> And we can see a couple of red colored errors in the shadps4 command line:
> 
> ```
> [Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=C:/InstalledGames/CUSA03173\dvdroot_ps4/menu/logo.tpf.dcx, error_message=no such file or directory
> [Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=C:/InstalledGames/CUSA03173\dvdroot_ps4/parts/wp_a_6010.partsbnd.dcx, error_message=no such file or directory
> [Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=C:/InstalledGames/CUSA03173\dvdroot_ps4/parts/lg_a_9700.partsbnd.dcx, error_message=no such file or directory
> [Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=C:/InstalledGames/CUSA03173\dvdroot_ps4/parts/lg_a_9700_l.partsbnd.dcx, error_message=no such file or directory
> [Kernel.Pthread] <Error> file_system.cpp:posix_stat:403: posix_stat: error = -2147352574
> [Common.Filesystem] <Error> io_file.cpp:Open:197: Failed to open the file at path=C:/InstalledGames/CUSA03173\dvdroot_ps4/menu/.gfx, error_message=no such file or directory
> ```
> 
> At this point, most sounds are missing from the game.
> 
> If we then proceed to properly save the game (that means exiting to Bloodborne's main menu, closing the emulator and starting it again so we are not greeted with the error message), the game will eventually have sounds again.

I don;t think this issue is related to this PR.
This issue is related to the 60fps +deltatime patch. if you don't mess with the game pace/fps, this does not happen.

**Comment by abouvier** [comment]
`externals/LibAtrac9` points to a commit on https://github.com/Vita3K/LibAtrac9, which is nonexistent on https://github.com/shadps4-emu/ext-LibAtrac9.

**Comment by GHU7924** [comment]
Build v0.4.1 WIP main f98b9f7

CUSA04943 (Gravity Rush 2), I know it doesn't work, but I always check my small list of games for any significant changes. Now there is such an error at startup.

ааа

**Pull request merged**
