### PR TITLE
recompiler: add use tracking

### PR DESCRIPTION
**Pull request by baggins183**
Add use tracking for instructions

Still want to add iterator adaptor for (distinct) users in addition to uses.

### CODE REVIEW

**Comment by baggins183** [comment]
on previous commit I stored uses (inst, index) in a list and used an adaptor to iterate over users.
That was broken though because apparently std:: or boost::unique modify the underlying container.
I changed it so per Inst, users are stored in a list, and nodes in the list hold a user + bitmask of the arg indices that use *this.
Needs a lot more lines of code. I wonder if there's to fix the old way so its simpler.

Still needs boost submodule update

**Comment by georgemoralis** [comment]
i don't see a pr for it on https://github.com/shadps4-emu/ext-boost :/

**Comment by georgemoralis** [comment]
@baggins183 if you can pr on boost the neccesary change so we can progress with that pr too

**Comment by baggins183** [comment]
@georgemoralis here u go boss
https://github.com/shadps4-emu/ext-boost/pull/9

**Comment by georgemoralis** [comment]
merge you need to update submodule here so we can see if it builds ;D

**Comment by baggins183** [comment]
Closing since most of this made it in with ssa fixes

**Pull request closed without merging**
