### PR TITLE
texture_cache: Enable anisotropic filtering

### PR DESCRIPTION
**Pull request by ngoquang2708**
Fixed blurry and smeared textures when viewed at an angle for games that use it.

### CODE REVIEW

**Comment by ngoquang2708** [comment]
Seem this just force AF in host side without considering setting from guest side. I will try to make this an override setting in config.

**Comment by Linear524** [comment]
Is it safe to just force AFx16 inside ?
I saw many cases in emulation, where forcing AFx16 broke some effects or caused some pixelated artifacts to appear...

**Comment by ngoquang2708** [comment]
Latest push only map guest sampler to host sampler, no forcing.

**Comment by ngoquang2708** [comment]
> I will try to make this an override setting in config.

This will be in a separate PR.

**Comment by rafael-57** [comment]
> Latest push only map guest sampler to host sampler, no forcing.

To the host's sampler? Does it mean it follows the settings in the GPU driver?

**Comment by ngoquang2708** [comment]
> To the host's sampler? Does it mean it follows the settings in the GPU driver?

Host's sampler means Vulkan sampler that we use. I don't know if we can override that setting at OS or driver level. Maybe we can.

**Review by raphaelthegreat — APPROVED** [review]

**Pull request merged**
