### PR TITLE
fix: compilation error seen in #234

### PR DESCRIPTION
**Pull request by ThatOneCalculator**

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Still needs testing

**Comment by abouvier** [comment]
You need to update the `sdl3` submodule too with this change.

**Comment by ThatOneCalculator** [comment]
What's the proper steps for updating the sdl3 submodule? Doing `git submodule update --remote --merge` yields the following diff:

```diff
commit 780e9ae0182e0d121bdaf57ef5849931ac1586e0 (HEAD -> fix/sdl-window-sdlk-inputs)
Author: ThatOneCalculator <kainoa@t1c.dev>
Date:   Thu Jul 4 19:47:08 2024 -0700

    test

diff --git a/externals/boost b/externals/boost
index 87b7817..dfb313f 160000
--- a/externals/boost
+++ b/externals/boost
@@ -1 +1 @@
-Subproject commit 87b7817119982e8ad6068855fae31b11590514be
+Subproject commit dfb313f8357b8f6601fa7420be1a39a51ba86f77
diff --git a/externals/glslang b/externals/glslang
index 33c7e30..5939e32 160000
--- a/externals/glslang
+++ b/externals/glslang
@@ -1 +1 @@
-Subproject commit 33c7e30860928bab3819c3abae8297b109a02f73
+Subproject commit 5939e32b87487fa9c72ab336ebfcc5ae26d9ab6d
diff --git a/externals/magic_enum b/externals/magic_enum
index dd6a39d..ec1adc5 160000
--- a/externals/magic_enum
+++ b/externals/magic_enum
@@ -1 +1 @@
-Subproject commit dd6a39d0ba1852cf06907e0f0573a2a10d23c2ad
+Subproject commit ec1adc5763f684e0f32888b157bfc0b86021b8e9
diff --git a/externals/toml11 b/externals/toml11
index b389bbc..edbea2f 160000
--- a/externals/toml11
+++ b/externals/toml11
@@ -1 +1 @@
-Subproject commit b389bbc4ebf90fa2fe7651de3046fb19f661ba3c
+Subproject commit edbea2f483f1c7f6e4a2439ebdbef1f07d7b4807
diff --git a/externals/vma b/externals/vma
index feb11e1..257138b 160000
--- a/externals/vma
+++ b/externals/vma
@@ -1 +1 @@
-Subproject commit feb11e172715011ef2a7b3b6c7c8737337b34181
+Subproject commit 257138b8f5686ae84491a3df9f90a77d5660c3bd
```

**Comment by abouvier** [comment]
> What's the proper steps for updating the sdl3 submodule?

You can't. Someone in charge needs to sync https://github.com/shadps4-emu/ext-SDL with upstream first.

**Comment by georgemoralis** [comment]
the reason we use a fork of sdl is to be able to watch for the changes more easy , i will do an update to latest sdl today

**Pull request closed without merging**
