### PR TITLE
DS_SWIZZLE_B32 - improvement

### PR DESCRIPTION
**Pull request by DanielSvoboda**
This pull request enhances the DS_SWIZZLE_B32 function to handle all swizzling modes described in the architecture documentation more robustly and flexibly.

Updated the DS_SWIZZLE_B32 function to support multiple data swizzling modes. The changes implement the logic for the following modes:

FFT Mode:
Implements the FFT algorithm using offset[4:0] to calculate the target data position.
Details: Added logic to apply an offset mask and adjust the position based on offset to support FFT operations.

Rotation Mode:
Implements data rotation using offset[9:5] to define the number of positions to rotate and offset[15] to determine the rotation direction (left or right).
Details: Added logic for conditional rotation based on the value of offset[15], adjusting the data position as needed.

Full Data Sharing Mode:
Allows data sharing between 4 consecutive threads when offset[15] == 1.
Details: Added logic to calculate the group_id and adjust data positions based on a group of 4 threads, supporting data exchange between them.

Limited Data Sharing Mode:
Implements data sharing between 32 threads using XOR, OR, and AND masks when offset[15] == 0.
Details: Added logic to apply bitwise masks to permute data among 32 consecutive threads, adjusting data positions as necessary.

Additional Details
**FFT Mode**: Utilizes an offset mask to calculate the correct data position, supporting specific FFT operations.
Rotation Mode: Adjusts data positions based on conditional rotation, depending on the value of offset[15].
**Full Data Sharing Mode**: Facilitates data exchange between threads in groups of 4, using the group_id to determine the position.
**Limited Data Sharing Mode**: Uses bitwise operations to permute data among 32 consecutive threads, offering flexibility for various data configurations.

### CODE REVIEW

**Comment by ryzendew** [comment]
any game that needs testing?

**Comment by DanielSvoboda** [comment]
Games that are graphically intensive and use custom shaders can benefit from commands like DS_SWIZZLE_B32.
AAA games like CUSA07439 can use these features, although no specific games have been confirmed to do so yet.
To see the impact of these changes, you'll need to test with games that make intensive use of graphics and shaders, but none of them work for testing purposes yet.
This PR includes additional details based on the VEGA and RDNA3 documentation, which are the same in this regard, and which provide a more complete description compared to GCN3. The gcn3 documentation seems to contain little information about it.

rdna3 page 522
https://www.amd.com/content/dam/amd/en/documents/radeon-tech-docs/instruction-set-architectures/rdna3-shader-instruction-set-architecture-feb-2023_0.pdf

gcn3 page 269
https://www.amd.com/content/dam/amd/en/documents/radeon-tech-docs/instruction-set-architectures/gcn3-instruction-set-architecture.pdf

**Comment by DanielSvoboda** [comment]
If this is not present in the GCN documentation, then it should not be implemented, right?

**Comment by ghost** [comment]
+1 docs and reference match code pretty well tbh

**Comment by rafael-57** [comment]
Curious if this would this address errors like this?  "X requires swizziling"

[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:393: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Render.Vulkan] <Warning> vk_compute_pipeline.cpp:BindResources:108: Metadata update skipped
[Render.Vulkan] <Warning> vk_compute_pipeline.cpp:BindResources:108: Metadata update skipped
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01] ####
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 2) requires swizzling [RG01] ####
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 1) requires swizzling [R001] ####
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.VideoOut] <Info> video_out.cpp:sceVideoOutGetFlipStatus:195: count = 1382, processTime = 106250000, tsc = 6498774354217, submitTsc = 6498719993588, flipArg = 1381, gcQueueNum = 0, flipPendingNum = 0, currentBuffer = 1
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitAndFlipCommandBuffers:2039: called [buf = 2]
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitCommandBuffers:2063: called
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitDone:2139: called
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 1) requires swizzling [R001] ####
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 1) requires swizzling [R001] ####
[Render.Vulkan] <Error> image_view.cpp:ImageViewInfo:87: Storage image (num_comps = 1) requires swizzling [R001] ####

**Comment by red-prig** [comment]
> swizzling

image swizzling is not related to the DS_SWIZZLE_B32 command, they are literally different things

**Comment by psucien** [comment]
Thank you for the implementation. However, we don’t expect this esoteric mode to be used by games, as it seems to have been designed primarily for computational kernels. We will return to this PR if evidence to the opposite appear.

**Pull request closed without merging**
