### PR TITLE
Skip GUI if launching a game directly

### PR DESCRIPTION
**Pull request by kalaposfos13**
Implements the suggestion in https://github.com/shadps4-emu/shadPS4/issues/1499

### CODE REVIEW

**Comment by kalaposfos13** [comment]
Now instead of opening a game with shadps4 {path/to/eboot.bin}, you can now do this:
shadps4 --game CUSAXXXXX --show-gui --patch {path/to/patch/file}
Reading the source code or running shadps4 --help will give further info.
Opening game by ID is done by checking each game install folder, and seeing if there is a folder named CUSAXXXX in them, and if so, opens {installdir}/CUSAXXXXX/eboot.bin.

**Comment by georgemoralis** [comment]
i wonder if that can somehow merge with #1349 and use boost program_options for flexability

**Comment by kalaposfos13** [comment]
I'm guessing by "merging" you mean "rewriting my solution to also use Boost", right? Probably doable, from what I've seen on said PR, and it would be not that hard as that also uses maps, just differently, though I've never used that library, so I'll have to learn it.

**Comment by georgemoralis** [comment]
it is not bad , but might be cleaner that way, i will pass it to @LNDF since he was the one than purpose boost :D

**Comment by LNDF** [comment]
> it is not bad , but might be cleaner that way, i will pass it to @LNDF since he was the one than purpose boost :D

To be able to use boots, program_options needs to be added to ext-boots. As an alternativem, a header only more lightweight library can be used (such as tclap).

**Pull request merged**
