### PR TITLE
Handle swapchain recreation

### LINKED ISSUE #1781: [Wayland] All games launch to a black screen with DISPLAY env var set
This is the remaining issue from the now-closed https://github.com/shadps4-emu/shadPS4/issues/1045.

Running the emulator on a Wayland compositor with a set DISPLAY environment variable causes all games launch with a black screen.

`unset DISPLAY; shadps4` is a workaround.

### PR DESCRIPTION
**Pull request by ngoquang2708**
Fix black screen in XWayland.

I have very limited knowledge about Vulkan. Let me know if I did anything wrong.

Fix: https://github.com/shadps4-emu/shadPS4/issues/1781, https://github.com/shadps4-emu/shadPS4/issues/1817.

### CODE REVIEW

**Comment by JetPackAndButlers** [comment]
Everything seems to launch fine
image
image
image
image

**Comment by Fuoxden** [comment]
Vulkan seems to be fixed for me! Thank you for this bug fix! Hope This gets merged!
Screenshot From 2024-12-23 00-10-52
Screenshot From 2024-12-23 00-10-01
Screenshot From 2024-12-23 00-13-10

**Comment by C0rn3j** [comment]
Looks like it indeed fixed #1781 for me, thank you very much for this!

**Comment by rharish101** [comment]
Unfortunately, this didn't fix the issue for me. I'm running Hyprland on Arch Linux, with an AMD RX 7900 XTX (RADV driver), and ran the latest git version of shadps4 from the AUR (https://aur.archlinux.org/packages/shadps4-git). The workaround of unsetting the `DISPLAY` var works though.

**Comment by ngoquang2708** [comment]
@rharish101 Could you try this https://github.com/shadps4-emu/shadPS4/pull/1860.

**Comment by rharish101** [comment]
> @rharish101 Could you try this #1860.

Thanks a lot, that fixes the issue for me!

**Comment by ngoquang2708** [comment]
@rharish101 If so please report to that PR.

**Pull request merged**
