### PR TITLE
 vulkan: Disable exceptions for getImageFormatProperties and account for errors.

### PR DESCRIPTION
**Pull request by squidbus**
Potential fix for https://github.com/shadps4-emu/shadPS4/issues/894. Check for possible errors from `getImageFormatProperties` and fall back to single sampling.

Needs to be verified as I don't have a reproducible system/game. If it does not fix please provide more details on the crash for investigation.

### CODE REVIEW

**Comment by 0xZ3n0x** [comment]
I could not reproduce the error with this one. For me, it seems to error have been resolved.

System:
OS: Windows 10
CPU: AMD Ryzen 5 5600
GPU: AMD Radeon RX 7600 XT (24.20.11.01)
RAM: 16GB

**Comment by raphaelthegreat** [comment]
I think a better way might be to disable exceptions just for this file

**Comment by squidbus** [comment]
> I think a better way might be to disable exceptions just for this file

Can you elaborate on how to do this as its not something I've done before.

**Comment by raphaelthegreat** [comment]
Vulkan Hpp has a macro VULKAN_HPP_NO_EXCEPTIONS that you can add to the top of this file to disable exceptions. Ideally we should enable it globally but will require a bit more work to adjust existing functions (The hpp repo has a list of all available macros as well https://github.com/KhronosGroup/Vulkan-Hpp)

**Comment by squidbus** [comment]
Okay, done.

**Pull request merged**
