### PR TITLE
Make AvPlayerQueue size atomic

### PR DESCRIPTION
**Pull request by OFFTKP**
std::queue::size is not thread safe, and also

```cpp
if (Size() == 0) {
    return std::nullopt;
}
std::lock_guard guard(m_mutex);
auto result = std::move(m_queue.front());
m_queue.pop();
```
doesn't look thread safe, because the Size() == 0 check can be false, but before the mutex is locked a different thread pops an element or clears the queue making size 0, which leads to UB

Added another size check after locking the mutex instead of locking it at the start of the function, so that Pop doesn't unconditionally lock but it also doesn't try to pop from an empty queue

### CODE REVIEW

**Comment by roamic** [comment]
This is a SPSC queue, the described scenario can never happen. This mutex is redundant.

**Comment by OFFTKP** [comment]
> This is a SPSC queue, the described scenario can never happen. This mutex is redundant.

What do you mean by "this mutex is redundant"? The mutex was already there and std::queue by itself is not thread safe even in SPSC.

**Comment by roamic** [comment]
Please describe a scenario where this will be a problem in SPSC.

**Comment by OFFTKP** [comment]
Is it SPSC? AvPlayerSource::GetVideoData calls ::Pop, and as far as I can see that gets called from sceAvPlayerGetVideoData, and also gets called from VideoDecoderThread for example. That's two places that call Pop is it not?

**Comment by roamic** [comment]
`GetVideoData` call `Pop` on `m_video_frames`. `VideoDecoderThread` does not call `Pop` on this queue.

**Comment by OFFTKP** [comment]
And only one thread can call sceAvPlayerGetVideoData at a time?

**Comment by roamic** [comment]
> And only one thread can call sceAvPlayerGetVideoData at a time?

Correct.

**Comment by OFFTKP** [comment]
Then in that case if these queues are externally synchronized everywhere the mutex can be removed and PR can be closed. If they aren't synchronized externally then the mutex can't be removed because std::queue is not thread safe in SPSC. This sort of middle state of "sorta MPMC safe but sorta not" is just very misleading if you decide to keep the mutex.

**Comment by roamic** [comment]
The `std::queue` is "externally" synchronized by this `mutex`. `queue::size` has no need to be synchronized because it's just reading an integral variable from `std::queue`. If It's 0 in the consumer thread then it will just wait for producer to push values. I'm sorry but I do not understand your case.

**Comment by OFFTKP** [comment]
> The `std::queue` is "externally" synchronized by this `mutex`. `queue::size` has no need to be synchronized because it's just reading an integral variable from `std::queue`. If It's 0 in the consumer thread then it will just wait for producer to push values. I'm sorry but I do not understand your case.

My response was to you saying "this mutex is redundant". This PR does not add a mutex, so I am assumed you meant we should remove the original mutex that was already there

**Comment by roamic** [comment]
This was bad wording on my part, sorry. The `mutex` that synchronizes `Push` and `Pop` is not redundant. I meant that the change as a whole is redundant in SPSC scenario.

**Pull request closed without merging**
