### PR TITLE
Some bloodborne hacks

### PR DESCRIPTION
**Pull request by raphaelthegreat**
Mostly a few hacks to allow retail game to boot. Not mergable but we can have this around for people to test while features are getting properly implemented in main

### CODE REVIEW

**Comment by KioryFreeman** [comment]
Amazing update on this one, FPS seems really consistent now and definitely steps into playable territory.

**Comment by noxifoxi** [comment]
At this point we should call the emulator **chadPS4**.

chadps4
*Sorry, but I couldn't hold it.*

**Comment by MaxMo20** [comment]
Question, are these hack temporary? I'm assuming they are but i don't like to assume anything that I'm unsure about. I didn't know there was motion blur in the first place, must be per object motion blur which I like and smoothens the objects in motion without too much blur.  Maybe when this is playable could we configure the motion blur amounts since we have the values or any of these hacks individually? Thanks!

**Comment by HermitsA** [comment]
OS: Nixos unstable (24.11)
GPU: RX 6700xt
CPU: Ryzen 5 7600
RAM: 32GB DDR5 6000 Mhz

It seems that the latest appimages for bb-hacks linux-qt has had a few regressions making the game unable to get to the menu.

Last seen working:
https://github.com/shadps4-emu/shadPS4/actions/runs/10458195832

Regressed at: https://github.com/shadps4-emu/shadPS4/actions/runs/10524940281
Also seen in: https://github.com/shadps4-emu/shadPS4/actions/runs/10526470363

[shad_log.txt](https://github.com/user-attachments/files/16736577/shad_log.txt)
360984682-57478af3-d7aa-4571-8f6e-10fbb4056f1a

**Comment by rafael-57** [comment]
Latest has some regressions, the code for skipping these...shaders? is gone so crash on death happens again:
image

Tested by manually putting this piece of code back and crash on death doesn't happen anymore.

**Comment by rafael-57** [comment]
Hunter's Dream actually works now!! Game is unmodded!

New game -> Die to the wolf -> Hunter's Dream!

image
[shad_log.txt](https://github.com/user-attachments/files/16803017/shad_log.txt)

Before this, trying to load a save crashed 2 the emu two times in a row though, not sure why. Haven't been able to replicate for now. Will provide logs if it happens again.

**Comment by rafael-57** [comment]
Lightning is still kinda broken (this is an interior scene)

image

**Comment by TedMosly** [comment]
infinite health cheat doesn't work, only stamina

**Comment by echolessowl** [comment]
tried the linux-qt version, was able to load character creator but immediately crashed after 'finalizing contract' with a `[Debug] <Critical> page_manager.cpp:GuestFaultSignalHandler:207: Unreachable code!` error

**Comment by raphaelthegreat** [comment]
Very few hacks are needed anymore before game boots, so this is not worth it to maintain anymore. Closing as main will soon be able to boot without any hacks

**Pull request closed without merging**
