### PR TITLE
Update building-linux.md

### PR DESCRIPTION
**Pull request by zqpvr**
add git to arch and fedora

### CODE REVIEW

**Comment by ryzendew** [comment]
Both arch and fedora come with git by default even on vanilla installs they changed that long ago.

**Comment by abouvier** [comment]
> Both arch and fedora come with git by default even on vanilla installs they changed that long ago.

None of Arch base packages depends on `git`.

**Comment by ryzendew** [comment]
> > Both arch and fedora come with git by default even on vanilla installs they changed that long ago.
> 
> None of Arch base packages depends on `git`.

I just did both a by hand install and archinstall and git was installed with both … I don’t say words for nothing i test before speaking like people should

**Comment by abouvier** [comment]
> > > Both arch and fedora come with git by default even on vanilla installs they changed that long ago.
> > 
> > 
> > None of Arch base packages depends on `git`.
> 
> I just did both a by hand install and archinstall and git was installed with both … I don’t say words for nothing i test before speaking like people should

Can you do `pacman -Qi git` and paste the line starting with `Required By`?

**Pull request closed without merging**
