### PR TITLE
gui: Implement gui translations

### PR DESCRIPTION
**Pull request by dima-xd**
Requsted by https://github.com/shadps4-emu/shadPS4/issues/540

### CODE REVIEW

**Comment by dima-xd** [comment]
Alright, I don't want to touch linux anymore. Can somebody tell me how do I install qt's LinguistTools in it?

**Review by Xphalnos — APPROVED** [review]
Works perfectly for French language. It would be nice to find a fix for the Linux build

**Comment by dima-xd** [comment]
Needs testing on linux and mac

**Comment by georgemoralis** [comment]
works great :D

**Comment by abouvier** [comment]
Is it really necessary to upload the translation directory inside the release archive when you already embedded it in the binary with `qt_add_resources()`?

**Comment by dima-xd** [comment]
> qt_add_resources

I think you're right. It should work without translations directory

**Pull request merged**
