### PR TITLE
Added fancy formating to the README and made some texts "better"

### PR DESCRIPTION
**Pull request by CyntexMore**
Added some notes with GitHub's Markdown alerts feature. — [Read more about it here.](https://github.com/orgs/community/discussions/16925)

Changed some texts to make them sound better.

I appreciate if you read this,
CyntexMore

### CODE REVIEW

**Comment by CyntexMore** [comment]
Oh, another thing. [This](https://github.com/shadps4-emu/shadPS4/pull/569/commits/1e90f4594105c5e14f3d9099572dc765ab0e8d7a) commit contains the main changes, and [this](https://github.com/shadps4-emu/shadPS4/pull/569/commits/41a93dcae41d4c977d430978ba5b01a4ed03e108) commit contains one thing that I accidentally left out from the first commit. My apologies for multiple commits with the same name, I did it this way so if it gets merged with the `main` branch of shadPS4 the main changes appear as the commit message.

**Comment by Xphalnos** [comment]
This is good work! I think it would be good to replace Dysmantle in "Status" with BloodBorne. Here is the link to the video: https://youtu.be/wC6s0avpQRE

**Comment by CyntexMore** [comment]
Sure thing! Done!

**Comment by georgemoralis** [comment]
Keyboard qt mapping isn't in main now so it should be exclude from Readme atm

**Comment by CyntexMore** [comment]
Sorry I didn't realize that, I've updated the README.

**Pull request merged**
