### PR TITLE
Fix download Cheats/Patches on Linux

### PR DESCRIPTION
**Pull request by DanielSvoboda**

### CODE REVIEW

**Comment by abouvier** [comment]
What distribution are you using? OpenSSL should already be linked to Qt6Network.

**Comment by DanielSvoboda** [comment]
I only use Windows 10 Pro.
However, several people reported to me that the download was not working on Linux. And just adding Qt6Network doesn't work.

**Comment by abouvier** [comment]
It works fine on Arch Linux.
It's weird to link a library when no file in the source tree uses this library directly.

**Comment by abouvier** [comment]
I maintain that this is a bad solution for a problem that comes from elsewhere.
The library will not even be linked if you have `-Wl,--as-needed` in your `LDFLAGS`.

**Comment by DanielSvoboda** [comment]
this worked for compilation with the github action. I don't know how to solve it any other way, if possible make a PR with a better solution, because I don't understand this part.

**Pull request merged**
