### PR TITLE
misc: Polish localization updates

### PR DESCRIPTION
**Pull request by mavethee**
## Translation changes for `Polish`:

- Corrected machine translations,
- Translate more strings and used,
- Language selection now can be translated (thanks to `QObject::tr`),
- (This is stupid but ?) Buttons like `Yes` and `No`s should be localized by default in Qt, but that doesn't seem to work, so added manually,
- Added translation for trophy popup, following Sony's locale:
  <details>
  
  **Real PS4:**
    CleanShot 2024-11-21 at 17 17 53@2x

   **shadPS4:**
  image

  </details>

Other languages can be updated with `lupdate` but that removes copyright so need to figure out way avoid that and have that process automatic, ig that's why previous PR was dead in the water for me.

### CODE REVIEW

**Comment by georgemoralis** [comment]
@DanielSvoboda can you look that translate files updates?

**Comment by mavethee** [comment]
> @DanielSvoboda can you look that translate files updates?

it's like asking can you check google translate 🤓 but we had that conversation before.

**Comment by georgemoralis** [comment]
i meant to check the other language files update ;/

**Comment by mavethee** [comment]
> i meant to check the other language files update ;/

I can do that, but again `lupdate` removes copyright so just for the note, this emu doesn't have any docs regarding translation files so i'm copying my behavior from DuckStation 😓
 
Added translation for trophy popup, following Sony's locale:
<details>

CleanShot 2024-11-21 at 17 17 53@2x

</details>

**Comment by mavethee** [comment]
Okay not entirely sure why #include can't pick up QObject like it should, damn adding features without making strings translatable. 🤔

**Comment by ghost** [comment]
How many polacks does it take to fix an emulator?

**Comment by mavethee** [comment]
> How many polacks does it take to fix an emulator?

Localization is not a fix 👻 

CleanShot 2024-11-21 at 19 03 12@2x

**Comment by DanielSvoboda** [comment]
> @DanielSvoboda can you look that translate files updates?

I'll see if I can help with anything this weekend.

**Comment by mavethee** [comment]
I guess I've tried what I've wanted, no idea how to ensure that SDL builds ignore Qt components.

**Comment by mikusp** [comment]
Some of those translations sound funny, like I wouldn't have guessed that it's about shaders 😄 
```
        <source>Enable Shaders Dumping</source>
        <translation>Włącz zgrywanie cieni</translation>
```

**Comment by mavethee** [comment]
> Some of those translations sound funny, like I wouldn't have guessed that it's about shaders 😄
> 
> ```
>         <source>Enable Shaders Dumping</source>
>         <translation>Włącz zgrywanie cieni</translation>
> ```

@mikusp It's already part of `main` and it's not incorrect, you're just used to English terms as any person peeking in debug tab.

Shaders = cienie, we have English words in our vocab, but you don't call every shadow a shader ;)
Dump = zgrywać, this is more about the action, emulator does rather than literal translation lul.

So whatever drives, I just need help with SDL builds because my C++ isn't that great yet and it's pretty much done.

**Comment by Hermiten** [comment]
I think this one is outdated now because of the recent change.
Are you planning to update it @mavethee ?

**Pull request closed without merging**
