### PR TITLE
Basic AvPlayer implementation

### PR DESCRIPTION
**Pull request by roamic**
Basic implementation of sceLibAvPlayer.

Details:
This library is used to demux and decode audio and video data from various sources.

The game provides the number of Video Frame Buffers and this library allocates the memory for them using the provided memory callbacks. The alignment of `0x100` for Video Frame Buffers was chosen by trial and error and might not be correct. I could not find the correct alignment in RE.

There are 4 total working threads per AV Player instance:
1. Controller thread. Used to perform costly operations by pushing an operation event into this thread. This allows the calling thread to do some other tasks in the meantime.
2. Demuxer thread. Used to demux the container and create packets for the enabled audio and video streams. If more than 8 audio frames and more than 30 video frames are produced it waits for them to be drained before continuing to save memory and CPU.
3. Video Decoder thread. Decodes the video packets and produces video frames in the Video Frame Buffers. If no Frame Buffers are available it waits for one.
4. Audio Decoder thread. Same, but for audio.

Missing Features:
* Jump To Time
* Pause/Resume
* HTTP Live Streaming - easy to implement with AVIO later if needed.
* Trick Mode
* AV Sync Mode - currently it syncs to audio **and** video, which is not correct, need to re-evaluate.

### CODE REVIEW

**Comment by gandalfthewhite19890404** [comment]
For tracking - Rayman Legends does not boot at all with that PR.

**Comment by georgemoralis** [comment]
Log might be useful

**Comment by gandalfthewhite19890404** [comment]
> Log might be useful

Honestly - same as in main build. Difference is - with that PR - infinite black screen.
On main - menus at least.

**Comment by gandalfthewhite19890404** [comment]
[shad_log_main.zip](https://github.com/user-attachments/files/16575971/shad_log_main.zip)
[shad_log_pr400.zip](https://github.com/user-attachments/files/16575972/shad_log_pr400.zip)

**Comment by StevenMiller123** [comment]
Your issue is unrelated to the PR, you need to add libSceUlt.sprx to your sys_modules folder.

**Comment by gandalfthewhite19890404** [comment]
Added lib ,and again - Rayman Legends does not boot at all with this PR. Those errors in log was even in main branch, but game was bootable.
[shad_log_pr400.zip](https://github.com/user-attachments/files/16576981/shad_log_pr400.zip)

**Comment by roamic** [comment]
In Rayman, the game supplies `'en'` as default language code, but the video only has `'eng'` which is not the same in the current logic. This is troublesome because now I need to find the code that converts language codes...

**Comment by Curioso9998** [comment]
With that, Ultimate Vs Capcom 3 even goes into the game but with many graphic errors

**Comment by Curioso9998** [comment]
another game that start is the Guilty Gear Xrd REV 2

**Comment by Curioso9998** [comment]
already hears significant improvement in Ultimate Vs Capcom 3

**Comment by bigol83** [comment]
Final Fantasy VII hangs when trying to reproduce opening, it just stays on a black screen after a couple of seconds with audio. 
Still FF VII when trying to reproduce Special Movie shows this error

Cattura


[shad_log.txt](https://github.com/user-attachments/files/16604573/shad_log.txt)

**Comment by Emulator-Team-2** [comment]
The opening movie now works in `BLAZBLUE CROSS TAG BATTLE` on the latest build, but there is a ghosting effect visible in the video and a glitch on the bottom of the screen.

<details> 
<summary>(Screenshots Comparisons)</summary>

**shadps4:**

**Movie:**


</details>

##

The game on this PR crashes on the title screen after pressing any button on the main build works fine.

Log:
[shad_log.zip](https://github.com/user-attachments/files/16605175/shad_log.zip)

**Comment by bigol83** [comment]
Resident Evil hd remaster still doesn't have audio in video for me

**Comment by roamic** [comment]
> Resident Evil hd remaster still doesn't have audio in video for me

I've checked the video files of RE HD Remaster and they do not contain a sound stream. This means that either my tools do not report a stream being present due to it being in unknown format (`ATRAC9` maybe?) or the sound files are played by the separate system from separate files (like /nativePS4/sound/movie/eng/wav/`).

**Comment by roamic** [comment]
> > Resident Evil hd remaster still doesn't have audio in video for me
> 
> I've checked the video files of RE HD Remaster and they do not contain a sound stream. This means that either my tools do not report a stream being present due to it being in unknown format (`ATRAC9` maybe?) or the sound files are played by the separate system from separate files (like /nativePS4/sound/movie/eng/wav/`).

Checked again and it's the latter. The game opens `/app0/nativePS4/sound/movie/eng/wav/titleLR_51.at9` alongside the intro movie for example. So AvPlayer has nothing to do with this.

**Comment by lzardy** [comment]
> Checked again and it's the latter. The game opens `/app0/nativePS4/sound/movie/eng/wav/titleLR_51.at9` alongside the intro movie for example. So AvPlayer has nothing to do with this.

I am doing Ngs2 currently, so perhaps it is this. I do not have RE to test however, but am testing on Gravity Rush Remastered.

**Comment by bigol83** [comment]
> > > Resident Evil hd remaster still doesn't have audio in video for me
> > 
> > 
> > I've checked the video files of RE HD Remaster and they do not contain a sound stream. This means that either my tools do not report a stream being present due to it being in unknown format (`ATRAC9` maybe?) or the sound files are played by the separate system from separate files (like /nativePS4/sound/movie/eng/wav/`).
> 
> Checked again and it's the latter. The game opens `/app0/nativePS4/sound/movie/eng/wav/titleLR_51.at9` alongside the intro movie for example. So AvPlayer has nothing to do with this.

I checked and there's actually a folder in game files with all the videos without sound. Sound for movies is in a separate folder encoded with at9, atrac9 files. I tried to reproduce them with at9player but it seems it doesn't work. I read that some of these files are encoded and must be decrypted. That is probably what emulator is missing.

**Comment by EmulationChannel** [comment]
[Debug] <Critical> memory.cpp:operator():220: Assertion Failed!
Existing mapping does not contain requested unmap range
[shad_log.txt](https://github.com/user-attachments/files/16629489/shad_log.txt)
Rayman Legends and all games my test PRs AVPlayer

**Comment by Curioso9998** [comment]
Ultimat marve vs capcom 3 only fata fix the performance this black area on the characters and the sound the control for some reason are not working

**Comment by Emulator-Team-2** [comment]
Tested with the latest build. 

The opening video in `BLAZBLUE CROSS TAG BATTLE` still has a visible ghosting effect and a glitch at the bottom of the screen.

##

The game still crashes on the title screen after pressing any button.

Log:
[shad_log.zip](https://github.com/user-attachments/files/16630314/shad_log.zip)

**Comment by roamic** [comment]
> [Debug] memory.cpp:operator():220: Assertion Failed! Existing mapping does not contain requested unmap range [shad_log.txt](https://github.com/user-attachments/files/16629489/shad_log.txt) Rayman Legends and all games my test PRs AVPlayer

This also happens on main if you wait in main menu long enough. With AvPlayer when you watch videos it just waits for you.

**Comment by roamic** [comment]
> Tested with the latest build.
> 
> The opening video in `BLAZBLUE CROSS TAG BATTLE` still has a visible ghosting effect and a glitch at the bottom of the screen.
> 
> The game still crashes on the title screen after pressing any button.
> 
> Log: [shad_log.zip](https://github.com/user-attachments/files/16630314/shad_log.zip)

The line at the bottom is the result of incorrect framebuffer size (1920x1088 instead of 1920x1080). This has nothing to do with the AvPlayer library itself as it provides the correct values for `width` and `height` of the video. As for the crash - it is a consequence of enabling the video. It creates additional textures when AvPlayer is initialized and tries to free them after. The issue is somewhere in other place.

**Pull request merged**
