### PR TITLE
Update renderdoc_app.h for larger MacOS Compatibility

### PR DESCRIPTION
**Pull request by N7z**

### CODE REVIEW

**Comment by raphaelthegreat** [comment]
Any updates to renderdoc header should be made into renderdoc upstream

**Comment by squidbus** [comment]
Can you explain what this is targeting? What macOS are you using that doesn't set `__APPLE__`?

**Comment by N7z** [comment]
> Can you explain what this is targeting? What macOS are you using that doesn't set `__APPLE__`?

Added __MACH__ check to ensure compatibility with systems using the Mach kernel, such as some NeXTSTEP-derived systems like OPENSTEP and Rhapsody.

**Comment by squidbus** [comment]
Well like was mentioned previously if you want to make a change to renderdoc you should go to the upstream, then pull from upstream into here.

**Pull request closed without merging**
