### PR TITLE
bb-hacks branch with key to controller mapping UI (not-mergeable, for testing purposes only)

### PR DESCRIPTION
**Pull request by VasylBaran**
This branch is based on bb-hacks branch with changes from "UI to configure keyboard-to-controller mapping" on top (from #308)

### CODE REVIEW

**Comment by georgemoralis** [comment]
At least you could open a pr on bb hacks branch..

**Comment by georgemoralis** [comment]
It is the only time I will permit pr's like that. Imagine if anyone that wants to add something to bb hacks branch do it similar. We will be full of bb hacks pr and that is not the purpose of the emu

**Comment by VasylBaran** [comment]
@georgemoralis I agree, thank you for understanding. Just wanted to make the people's life a bit easier since there are a lot of people joining just to play Bloodborne and I see them struggling with controls... and if I just made a new branch on my fork of shadPS4 then there would be no building pipeline to share will people so that's why I've created a draft pull request but again - I understand that it's wrong and I promise not to abuse this in the future. 

Thank you for understand, George

**Comment by raphaelthegreat** [comment]
Please don't open PRs like this. People can test it when it's merged, otherwise we will have many people do this and will be a nightmare

**Comment by VasylBaran** [comment]
@raphaelthegreat I understand, thank you

**Comment by raphaelthegreat** [comment]
If you want people to test your build on BB I recommend you setup actions on your repo and have a branch there

**Pull request closed without merging**
