### PR TITLE
vk_shader_hle: Don't alter the order of the skipped copies.

### LINKED ISSUE #1752: Bloodborne Textures Deload
Since the merging of the two HLE [e5e1aba](https://github.com/shadps4-emu/shadPS4/commit/e5e1aba24172b4cf41e1c4ea56adf0b0984b815b) brunches and the double-delete [41fd1c8](https://github.com/shadps4-emu/shadPS4/commit/41fd1c84cf51fbb8b3784e038c72d4bb37b8f406), the game has seen an increase in texture deloading. Since July, on my system I have not encountered this once on shadps4 (on ps4 pro encountered), but after the latest version of HLE merged into the main build, it happens all the time in different parts of any location. Most noticeable at the very beginning of the game, if you don't go to the hunter's dream and make your way down the main street:
image
Also a signal of such a problem is the presence of a vertex explosion in the player character from a "cold start" of the emulator at the beginning of a new game.

### PR DESCRIPTION
**Pull request by dcealopez**
From my limited testing this should fix [1752](https://github.com/shadps4-emu/shadPS4/issues/1752) but it needs proper testing.

### CODE REVIEW

**Comment by sam20112011** [comment]
Based on my testing method, despite the returned error "unsupported pm4 type 0", the deload problem is solved. Need fideback from more players. But it's promising).

**Comment by Missake212** [comment]
Tested commit 359b869 and saw no missing geometries, should we also test the new commit you pushed 15 minutes ago?

**Comment by dcealopez** [comment]
> Tested commit [359b869](https://github.com/shadps4-emu/shadPS4/commit/359b8692278ec5d11f49bb722aa83e19a4474d67) and saw no missing geometries, should we also test the new commit you pushed 15 minutes ago?

Nice. Thanks for testing!
To answer your question, there's no code changes, so no. I just squashed the commits.

**Comment by sam20112011** [comment]
Cheers, man).

**Comment by dcealopez** [comment]
Many people have reported on Discord that this seems to fix the issue. Let me know if this is good to go or if it needs any changes.

**Comment by sam20112011** [comment]
It looks to me like it's working fine. When it's merged into the main, I'll close the ticket.

**Comment by raphaelthegreat** [comment]
I think we might be starting to make the algorithm more complex than necessary. Can you try something simpler: when we encounter a copy we cant batch, instead of keep searching, stop and do copy.

**Comment by dcealopez** [comment]
> I think we might be starting to make the algorithm more complex than necessary. Can you try something simpler: when we encounter a copy we cant batch, instead of keep searching, stop and do copy.

Yup, agreed. Thanks for the suggestion! Seems to be working fine.
@sam20112011 @Missake212 @rainmakerv3 could you repeat your testing with the latest commit please?

**Comment by sam20112011** [comment]
Yeap.

**Comment by sam20112011** [comment]
Well the last commit works fine for me)

**Pull request merged**
